### ISSUE TITLE
Error when trying to export a database and import it into another file

### ISSUE THREAD

**Issue by denjucks** [eveningkid/denodb#10]
I am trying to create a database in one file, export it, and then import it into another file for use in that file. When I try to export and import it, I get the following error:

```
error: Uncaught ReferenceError: Cannot access 'database' before initialization
database.link([MyModel]);
^
    at file:///test.js:5:1
    at <anonymous> (<anonymous>)
```

Here is the file where I am exporting the database:
```javascript
import { Database } from 'https://deno.land/x/denodb/mod.ts';

export const database = new Database("sqlite3", {filepath: "test.db"});
```

And here is the file where I am importing it:
```javascript
import { database } from "./import_file.js";
import { MyModel } from "./model_file.js";

database.link([MyModel]);
```

Awesome library by the way! Glad to see dex being included in this library, very well done!

**Comment by eveningkid** [comment]
Hey,

This is odd, I don't think it comes from the library itself.

I tried to do exactly what you did and didn't get the error, here's my code (coming straight from the README I admit hehe):
```typescript
// database.js
import { Database } from "https://deno.land/x/denodb/mod.ts";

export const database = new Database("sqlite3", {
  filepath: "./db.sqlite",
});

// model.js
import { DATA_TYPES, Model } from "https://deno.land/x/denodb/mod.ts";

export class Flight extends Model {
  static table = "flights";
  static timestamps = true;

  static fields = {
    id: {
      primaryKey: true,
      autoIncrement: true,
    },
    departure: DATA_TYPES.STRING,
    destination: DATA_TYPES.STRING,
    flightDuration: DATA_TYPES.FLOAT,
  };

  static defaults = {
    flightDuration: 2.5,
  };
}

// db.js, your test.js file
import { database } from "./database.js";
import { Flight } from "./model.js";

database.link([Flight]);

await database.sync({ drop: true });

await Flight.create([
  {
    departure: "Paris",
    destination: "Tokyo",
  },
  {
    departure: "London",
    destination: "San Francisco",
  },
]);

console.log(await Flight.all());

await database.close();
```

If you sure your three files I might try it again and see if it doesn't run on my side either. There must be something, a tiny mistake somewhere I believe.

Thanks for trying the library and also porting knex to deno!! I was actually half-way making my own SQL query builder when I found your lib and decided to rely on! 😄 

Keep in touch

**Comment by denjucks** [comment]
I tested this out a bit, and you are correct, this doesn't seem to be an issue with denodb. I was trying to get this working in the Oak framework by exporting it to routers, and then importing the routers back in the app file:


`app.js`
```javascript
import { Application } from "https://deno.land/x/oak/mod.ts";
import { Database } from 'https://deno.land/x/denodb/mod.ts';

const app = new Application();

//DB
export const database = new Database("sqlite3", {
    filepath: "test.db",
});

//Router
import router from "./router.js";
app.use(router.routes());
app.use(router.allowedMethods());

// Starting the server
await app.listen({ port: 8000 });
```

`router.js`
```javascript
import { Router } from "https://deno.land/x/oak/mod.ts";
import { database } from "./app.js";

// Error is thrown here
/*
error: Uncaught ReferenceError: Cannot access 'database' before initialization
console.log(database);
*/
console.log(database);

const router = new Router();

// Routes
router.get("/", async (context) => {
	context.response.body = "hello world";
});

export default router;
```

Any chance you know if something like this is possible? Also, I'm gonna close the issue, as this is more related to oak than denodb.

> I was actually half-way making my own SQL query builder when I found your lib and decided to rely on! smile
Happened to me a couple times too, its amazing how many and how quickly libraries are being developed and ported over to deno, especially since 1.0.0 released! Glad to see people are making and porting a lot of libraries!

**Comment by eveningkid** [comment]
Regarding your issue, I think it might be because imports are usually (I believe) loaded all at once, which means that even if you put it on another line, it will still try to import the file before you hit that line. So in that case, it would make sense that `database` is not yet defined.

I think a simple solution would be to have a `database.js` file which contains your `new Database(...)` call so you then can import it in both `router.js` and `app.js` (especially because there is no app-related constraint on your database, it can be declared in a separate file).

I am pretty sure this should solve your issue :)
