### ISSUE TITLE
Uncaught ReferenceError: Cannot access 'Model' before initialization

### ISSUE THREAD

**Issue by thang40** [eveningkid/denodb#105]
Hello, I encountered this error when trying to achieve one-to-many relationship
`error: Uncaught ReferenceError: Cannot access 'UserModel' before initialization
    userId: Relationships.belongsTo(UserModel),`

I have 2 models
Article
```
import {
  DataTypes,
  Model,
  Relationships,
} from "https://deno.land/x/denodb/mod.ts";
import { UserModel } from "./user.ts";
export class ArticleModel extends Model {
  static table = "articles";
  static timestamps = true;

  static fields = {
    id: { primaryKey: true, autoIncrement: true },
    content: DataTypes.TEXT,
    title: DataTypes.STRING,
    tags: DataTypes.ENUM,
    likeCount: DataTypes.INTEGER,
    userId: Relationships.belongsTo(UserModel),
  };

  static user() {
    return this.hasOne(UserModel);
  }
}

```
User
```import { DataTypes, Model } from "https://deno.land/x/denodb/mod.ts";
import { ArticleModel } from "./article.ts";

export class UserModel extends Model {
  static table = "users";
  static timestamps = true;

  static fields = {
    id: { primaryKey: true, autoIncrement: true },
    username: DataTypes.STRING,
    password: DataTypes.STRING,
  };

  static articles() {
    return this.hasMany(ArticleModel);
  }
}
```
Seems like a cyclic dependency problem here because User class references Article class and vice versa.
Please help

**Comment by hoangph271** [comment]
I think this is more of a coding problem than a denodb problem...!  
You can avoid cyclic dependency by just declaring all models in a single file...?

**Comment by felipeszu** [comment]
Same problem here! Any solution?

**Comment by gateaubleu** [comment]
Same for me, any solution ?

**Comment by gateaubleu** [comment]
Same for me
@eveningkid

**Comment by duart38** [comment]
same

**Comment by unuaunco** [comment]
Hi, guys
@thang40 @gateaubleu @duart38

There is the solution to connect all single-file models using single import (export?) file.
So, assuming, that we have `models` folder and `user.ts` and `./article.ts` file there. It needs to create `import.ts` file in the same folder that contains all exports for all connected models and each model should import from `import.ts` instead of other model file.

    models \
        article.ts
        import.ts
        user.ts

`import.ts`

````typescript
export { UserModel } from "./user.ts";
export { ArticleModel } from "./article.ts";
````

`user.ts`

````typescript
import { ArticleModel } from "./import.ts";

export class UserModel extends Model {
  //// ...
 }
````

`article.ts`

````typescript
import {
  DataTypes,
  Model,
  Relationships,
} from "https://deno.land/x/denodb/mod.ts";
import { UserModel } from "./import.ts";
export class ArticleModel extends Model {
  //// ...
 }
````

Also, all models' imports in app should be done through `import { ArticleModel, UserModel } from "./models/import.ts";`

**Comment by thang40** [comment]
@unuaunco It still looks cyclic dependency to me because `import.ts` depends on those 2 files and the same for `article.ts` and `user.ts`

**Comment by unuaunco** [comment]
@thang40 Can you write an example of your code (models, import.ts and usage)? And how do you import your models in a rest of the code?

**Comment by thang40** [comment]
@unuaunco it's just like I mentioned that I have 2 files `article.ts` and `user.ts` and it depends on each others

**Comment by unuaunco** [comment]
So have you tries to move exports to third file `import.ts` ? And change import statements in models to `import { ArticleModel } from "./import.ts";` ?
Also you need to import models through `import.ts` in a rest of your code

**Comment by thang40** [comment]
@unuaunco you missed the point that the dependencies between those files is cyclic 
`import.ts` depends on `user.ts` and `article.ts` because it import those 2 files
`user.ts` and `article.ts` depend on `import.ts` same reason

**Comment by stillalivx** [comment]
@eveningkid, I was checking this issue (I'm in this situation right now)... How about let pass the table name directly to the belongsTo parameter. Something like:
```typescript
export class ArticleModel extends Model {
  static table = "articles";
  static timestamps = true;

  static fields = {
    id: { primaryKey: true, autoIncrement: true },
    content: DataTypes.TEXT,
    title: DataTypes.STRING,
    tags: DataTypes.ENUM,
    likeCount: DataTypes.INTEGER,
    userId: Relationships.belongsTo("users"), // Here
  };

  static user() {
    return this.hasOne(UserModel);
  }
}
```
So we avoid falling in the typescript error @hoangph271 [said](https://github.com/eveningkid/denodb/issues/105#issuecomment-685909621). Solutions for desperate moments

**Comment by eveningkid** [comment]
Hey guys,

I think the way this could be done without cyclic dependencies is by taking the relationships outside of the model definition.

At the moment, if you make a one-to-one relationship (or many-to-many, etc.), it has to be done this way:

```js
import { Relationships } from 'https://deno.land/x/denodb/mod.ts';

// After both models declarations

Relationships.oneToOne(Business, Owner);

// Before database linking
```

I could change the `belongsTo` API so you could have:

```js
// models/article
export class Article extends Model {
  static table = "articles";
  static timestamps = true;

  static fields = {
    id: { primaryKey: true, autoIncrement: true },
    // ...
  };

  static user() {
    return this.hasOne(User);
  }
}

// app
// Create userId in Article
Relationships.belongsTo(Article, User);
```

Also, thank you so much for your patience. I only got back to help recently, didn't have the time before.

Anyways, let me know what you think or feel free to suggest another syntax :)

**Comment by thang40** [comment]
> Hey guys,
> 
> I think the way this could be done without cyclic dependencies is by taking the relationships outside of the model definition.
> 
> At the moment, if you make a one-to-one relationship (or many-to-many, etc.), it has to be done this way:
> 
> ```js
> import { Relationships } from 'https://deno.land/x/denodb/mod.ts';
> 
> // After both models declarations
> 
> Relationships.oneToOne(Business, Owner);
> 
> // Before database linking
> ```
> 
> I could change the `belongsTo` API so you could have:
> 
> ```js
> // models/article
> export class Article extends Model {
>   static table = "articles";
>   static timestamps = true;
> 
>   static fields = {
>     id: { primaryKey: true, autoIncrement: true },
>     // ...
>   };
> 
>   static user() {
>     return this.hasOne(User);
>   }
> }
> 
> // app
> // Create userId in Article
> Relationships.belongsTo(Article, User);
> ```
> 
> Also, thank you so much for your patience. I only got back to help recently, didn't have the time before.
> 
> Anyways, let me know what you think or feel free to suggest another syntax :)

This is what I'm looking for !

**Comment by eveningkid** [comment]
Alright, you can now upgrade to the latest version or at least to `v1.0.29` for using the new `Relationships.belongsTo(...)`!

You should now remove the foreign keys from your fields and create them before linking the models:

```js
Relationships.belongsTo(Article, User);
```

The documentation [has also been updated](https://eveningkid.com/denodb-docs/docs/guides/foreign-key#example).

I hope this fixes all your problems. Feel free to reopen if it doesn't, but let's be optimist!

Good day :)

**Comment by stillalivx** [comment]
Hey, @eveningkid. I have a little question. How can we name the fields where the FK will be?

In the docs show something like `ownerId`, but it wasn't declare in any Models.

**Comment by eveningkid** [comment]
@stillalivx the docs say "This will make `ownerId` a foreign key based on `Owner.id` primary key". It follows the naming convention first, but you can override it:

```js
Relationships.belongsTo(Business, Owner, { primaryKey: 'somethingElseId' });
```

Hope this clarifies everything :)
