### ISSUE TITLE
Database data changes not updated unless db is closed

### ISSUE THREAD

**Issue by iBuffering** [eveningkid/denodb#11]
I was trying to create a simple REST API using Oak just to get used to the Deno workflow. I followed the readme and succesfully created and linked my models and I managed to write to an sqlite database. Then when I decided to implement some controllers for creating records in the database I realized that as soon as the execution stopped my records where gone. I digged through your library (I'm kind of a noob so I took the chance to learn something) and I realized that the data isn't written to disk unless `db.close()` is called. I was wandering if I was doing something wrong or if there are some methods that I'm missing since I can't find a proper place to call that method building an API.

**Comment by eveningkid** [comment]
Hey Filippo,

You are right, I actually didn't realise how this would be a problem (to save the file on `.close`).
I think it makes very much sense to save the file after every query that alters the database.

I will update it now and this should solve your issue :)

**Comment by eveningkid** [comment]
This should now be ok. Just reload the library (using `--reload` with `deno run`) and that should do it.

Please reopen the issue if it doesn't! :)

Thanks for using denodb, any other feedback is very welcomed.
