### ISSUE TITLE
Cannot read property table of undefined

### ISSUE THREAD

**Issue by Danieliessen** [eveningkid/denodb#114]
I always get this error trying to create a database:
`error: Uncaught TypeError: Cannot read property 'table' of undefined
      this._currentQuery.table(this.table).create(
                         ^
    at Function.create (model.ts:261:26)
    at addUser (test.ts:7:16)
    at test.ts:35:1
    at <anonymous> (<anonymous>)
[finalconst@finalconst-rogzephyrusg14ga401iv AIOdeno]$ deno run -A --unstable test.ts 
Check file:///home/finalconst/Desktop/AIOdeno/test.ts
error: Uncaught Error: Unknown response for startup: E
          throw new Error(`Unknown response for startup: ${msg.type}`);
                ^
    at Connection.startup (connection.ts:173:17)
    at async Client.connect (client.ts:14:5)
    at async PostgresConnector._makeConnection (postgres-connector.ts:39:5)
    at async PostgresConnector.query (postgres-connector.ts:57:5)
    at async Database.query (database.ts:161:21)
    at async addUser (test.ts:7:5)`
(deno )1.3.3
NOTE: I could not run it on deno 1.3.3, thats why i copied the postgres connector 4.4 and denodb code in a local folder(since in deno land's third party modules there were no postgresql 4.4)

**Comment by eveningkid** [comment]
Hi,

I believe you're missing a `static table = 'users';` property in your `User` model.

If you still can't figure out what is the issue, share some code and I'll be able to help you out :)

Keep in touch

**Comment by Danieliessen** [comment]
`
const db = new Database('postgres', {
    host: 'localhost',
    username: 'postgres',
    password: 'Dortanian45',
    database: 'AIO',
  });

  class User extends Model {
    static table = 'users_table';
    static timestamps = true;
  
    static fields = {
      id: { primaryKey: true, autoIncrement: true },
      username: DataTypes.STRING,
      email: DataTypes.STRING,
      password: DataTypes.STRING,
    };
  
    static defaults = {
      username: "name",
    };
  }
  db.link([User]);
  await db.sync({ drop: true });
  await User.create({
    email: "emailo",
    username: "usernameo", 
    password: "passwordo"
});`
Nope, there is a users table, table name is users_table.
Thanks in advance..

**Comment by Danieliessen** [comment]
Works now (not on deno 1.4 though)

**Comment by Daniel-Knights** [comment]
I'm now getting the same error:
```bash
TypeError: Cannot read property 'table' of undefined
    at Function.create (model.ts:276:26)
    at create_post (PostsController.ts:13:14)
    at async dispatch (middleware.ts:39:7)
    at async dispatch (middleware.ts:39:7)
    at async dispatch (middleware.ts:39:7)
    at async dispatch (middleware.ts:39:7)
    at async Application.#handleRequest (application.ts:250:9)
```

My `Post` model:
```js
import { Model, DataTypes, Relationships } from 'https://deno.land/x/denodb/mod.ts';

import User from './User.ts';

class Post extends Model {
	static table = 'posts';
	static timestamps = true;

	static fields = {
		_id: { primaryKey: true },
		text: DataTypes.STRING,
		author: Relationships.belongsTo(User),
	};
}

export default Post;
```

Error occurs when I hit this route:
```js
// Create post
create_post: async (ctx: any) => {
	const req = await ctx.request.body().value;

	await Post.create({
		text: req.text,
		author: req.author,
	})
		.then(post => {
			ctx.response.body = { success: true, msg: 'Post created', post };
			ctx.response.status = 201;
		})
		.catch(err => {
                         // Error originates from here
			console.error(err);

			ctx.response.body = { success: false, msg: 'Unable to create post', err: err.message };
			ctx.response.status = 500;
		);
}
```

My DB config:
```js
import { Database } from 'https://deno.land/x/denodb/mod.ts';

// Models
import Post from '../models/Post.ts';
import User from '../models/User.ts';

// Connect
const db = new Database('mongo', {
	uri: '<URI>',
	database: 'deno_oak',
});

// Links
db.link([Post, User]);
db.sync({ drop: true });

export default db;
```

Using with Oak. 

Tried every combination of solutions I could think of but, no luck.

**Comment by trydalch** [comment]
For me, it was that I didn't call `db.link()`
