### ISSUE TITLE
Uncaught ReferenceError: Cannot access 'Model' before initialization

### ISSUE THREAD

**Issue by Danieliessen** [eveningkid/denodb#117]
error: Uncaught ReferenceError: Cannot access 'Model' before initialization
       export class PivotModel extends Model {
                                ^
        at model-pivot.ts:5:33

These errors occur **sometimes** in some of my projects.. Even if i reload deno cache..

**Comment by Danieliessen** [comment]
Does not occur anymore

**Comment by Redstoneguy129** [comment]
What was your fix?
