### ISSUE TITLE
How to get inserted row id(question)

### ISSUE THREAD

**Issue by Danieliessen** [eveningkid/denodb#119]
How to get inserted row id??

**Comment by eveningkid** [comment]
Hi Daniel,

I haven't tried it myself but I remember something like this was possible:
```js
const flight = Flight.create(...);
console.log(flight.id);
```
Give it a try and let me know if that works.

If it doesn't, share your code with us.

Keep in touch

**Comment by stillalivx** [comment]
When you create an element, the function returns a object with this data:
```
affectedRows, lastInsertId
```
So, like eveningkid said:
```javascript
const queryResult = await User.create(data);
console.log(queryResult.lastInsertId);
 ```

**Comment by eveningkid** [comment]
Thanks a lot @stillalivx, this should answer his question now :)

Feel free to reopen if it didn't @Danieliessen.

Have a great day guys
