### ISSUE TITLE
Relationships fails, when in separate modules.

### ISSUE THREAD

**Issue by dvlden** [eveningkid/denodb#120]
The example from [here](https://eveningkid.github.io/denodb-docs/docs/guides/one-to-many#example) simply fails if each Model goes into its own file.

Here's the error that is thrown:
```
error: Uncaught ReferenceError: Cannot access 'Owner' before initialization
    ownerId: Relationships.belongsTo(Owner)
```

What's the solution here?

**Comment by stillalivx** [comment]
Hi! This is the solution with doc's example:

This is the file with the db connection:
```typescript

import (...) // Imports from DenoDB

import Owner from "./owner.ts";
import Business from "./business.ts";

const db = new Database(...); // DB connection

db.link([Owner, Business]);

await db.sync({ drop: true });

// All the db queries...

await db.close();

export { Owner, Business }; // IMPORTANT

```

This is the Business model file:
```typescript
import (...) // Imports from DenoDB

import {Owner} from "./test.ts"; //IMPORTANT we are importing from the test.ts and not from owner.ts

export default class Business extends Model {
  //Model props and methods
}
```

This is the Owner model file:
```typescript
import (...) // Imports from DenoDB

import {Business} from "./test.ts"; //IMPORTANT we are importing from the test.ts and not from business.ts

export default class Owner extends Model {
  //Model props and methods
}
```

Tell me if this works!

**Comment by dvlden** [comment]
Yeah, that seems to work. However, this just doesn't seem natural at all.

Importing my models into the file that contains the connection, linking them, and exporting them, only to import them later from that file. 

Thanks for the help, but I decided to proceed with `deno_mongo` directly.

**Comment by kim0** [comment]
I found the answer provided here not to my taste as well, and starting considering other options (apart from denodb) as well. But I could resolve my issue through https://github.com/eveningkid/denodb/issues/105 .. so just leaving this here in case it helps someone else!
