### ISSUE TITLE
Eslint + Prettier file

### ISSUE THREAD

**Issue by rluvaton** [eveningkid/denodb#127]
Can you please create an _ESLint_ and _Prettier_ configuration files for this project's style so https://github.com/eveningkid/denodb/pull/125#issuecomment-696956255 mistakes won't happen?

**Comment by eveningkid** [comment]
Hi,

I am actually not using any, as deno has its [built-in formatter](https://deno.land/manual/tools/formatter) that you should use.

Same goes for their linter. I use their [vs-code plugin](https://marketplace.visualstudio.com/items?itemName=denoland.vscode-deno) which does all of it automatically.

If you are not using vs-code, you can simply use `deno fmt`

**Comment by rluvaton** [comment]
also, `tsconfig` needs to be added, because I'm having problems like 
> TS2339: Property 'entries' does not exist on type 'ObjectConstructor'.
for `Object.entries`

**Comment by Skillz4Killz** [comment]
Deno does not require a tsconfig file as it has 1 built in

**Comment by rluvaton** [comment]
> Deno does not require a tsconfig file as it has 1 built in
Yeah I know but it's weird that it shows me that error (I'm using WebStorm)
