### ISSUE TITLE
UnderScores are removed from column name (Postgres DB)

### ISSUE THREAD

**Issue by rshashik** [eveningkid/denodb#141]
Hi,
When we create table with column names having underscores , denodb prepares the data by removing the undescores and converting them to camel case. for e.g if column name in db is "test_column_name" , deno db changes it to "testColumnName".

**Comment by eveningkid** [comment]
Hi,

You are right, this was a mistake in the codebase (no idea why this was there).

It is now fixed with the new release!

Have a great day :)
