### ISSUE TITLE
Error: Unknown auth message code 10

### ISSUE THREAD

**Issue by JanWen** [eveningkid/denodb#142]
Trying to run simple example code below on windows 10 connecting to  my local postgres server produces some weird auth related error message. I can succesfully connect to the server using pgAdmin or pythons psycogs2 library.

**Error:**
```
Error: Unknown auth message code 10
    at Connection.handleAuth (connection.ts:197:15)
    at Connection.startup (connection.ts:155:16)
    at async Client.connect (client.ts:14:5)
    at async PostgresConnector._makeConnection (postgres-connector.ts:39:5)
    at async PostgresConnector.query (postgres-connector.ts:57:5)
    at async Database.query (database.ts:159:21)
    at async Function.drop (model.ts:103:5)
    at async Database.sync (database.ts:124:9)
    at async main (ok.ts:24:9)
```

**Code:**
```
import { Database, Model } from 'https://deno.land/x/denodb/mod.ts';

class User extends Model {
    static table = "users"
    static fields = {
        id: { primaryKey: true, autoIncrement: false },
    };
}


const main = async () => {
    const params = {
        host: "127.0.0.1",
        username: "postgres",
        password: "password",
        database: "postgres",
        port: 5432,
    }
    const db = new Database('postgres', params)

    try {
        db.link([User]);
        await db.sync({ drop: true });
    } catch (e) {
        console.log(e)
    }
}

main()
```

Please let me know if I can provider further help or information to solve this issue.

**Comment by EliSauder** [comment]
@JanWen It looks like it is an issue with the underlying postgres driver for deno

https://github.com/deno-postgres/deno-postgres/issues/182

**Comment by eveningkid** [comment]
Hey,

Just a quick update on this (I know it's been ages, sorry about that).

It seems to have been fixed very recently and since denodb is now using postgres@0.11.1, it shouldn't be an issue anymore.

Thanks again for raising the problem.

Good day :)
