### ISSUE TITLE
Allow null on a field with a relationship does not work

### ISSUE THREAD

**Issue by sntg-p** [eveningkid/denodb#145]
The resulting table ends up with a not null constraint, even when creating the field manually instead of using the Relationship helper functions:

```js
parentId: {
	type: DataTypes.INTEGER,
	allowNull: true,
	relationship: {
		kind: "single",
		model: Location,
	}
}
```

I also tried setting ```parentId: null``` in the static defaults object but the result is the same, the table ends up being created with a not null constraint.

I'm reading the code to see if I can find why this is happening.

**Comment by stillalivx** [comment]
Hi! I made changes weeks ago to put automatically the not null propertie... I'm gonna edit the code to allow the null value.
Can you tell me what data base (mysql, mongo, etc.) are you using?

**Comment by sntg-p** [comment]
Thank you! I'm using MariaDB.

**Comment by stillalivx** [comment]
Hey! I'm sorry, I was checking some issues about ```update_at``` before edit the code. Have you ever had errors when you update any field in your database?
I'm asking this 'cause I have a commit in my fork to resolve this issue and I don't wanna break your code if this is not your situation.

**Comment by sntg-p** [comment]
No problem! Actually yes, I was having problems with the automatically created timestamp fields but I just decided to stop using that option and it worked so I stopped trying to mess with it.

I just checked your repo and I remember finding your pull request when searching about that problem I was having, I was hoping your pull request got merged.

**Comment by stillalivx** [comment]
Alright! I did the changes. You can use my fork to import DenoDB while we wait the merge:
``` TypeScript
import { Database, Models, Relationships } from "https://raw.githubusercontent.com/stillalivx/denodb/master/mod.ts" 
```
If you have a problem, let me know. If you don't, please close the issue.

Good coding! 🙂
