### ISSUE TITLE
TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'

### ISSUE THREAD

**Issue by juslin03** [eveningkid/denodb#146]
Hey there, it has taken me already 3 weeks I'm trying to fix this and I didn't found a solution. 
In my code source, I created a file called `deps.ts` at my project root and I export **denodb** module `(export { Database } from "https://deno.land/x/denodb@v1.0.12/mod.ts";)`. When I run my server, I got many errors that I need help. Theses are errors `error: TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { LogLevels, LevelName } from "./levels.ts";
                    ~~~~~~~~~
    at https://deno.land/std@0.63.0/log/mod.ts:13:21

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  Deferred,
  ~~~~~~~~
    at https://deno.land/x/mysql@v2.5.0/deps.ts:3:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { Client, ClientConfig } from "./src/client.ts";
                 ~~~~~~~~~~~~
    at https://deno.land/x/mysql@v2.5.0/mod.ts:1:18

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { ObjectId, UpdateOptions } from "./ts/types.ts";
                   ~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/eveningkid/deno_mongo/master/mod.ts:5:20

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  ClientOptions as MongoDBClientOptions,
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/denodb@v1.0.12/unstable_deps.ts:11:3

Found 5 errors.`

Anyone got the same ? How to fix them ?
I use **Deno version 1.5.0, typescript 4.0.3**

**Comment by tsaulic** [comment]
Got the same errors, Deno 1.5.0 and 1.5.1. Would love a fix for this or any kind of workaround.

**Comment by stillalivx** [comment]
It seems the issue comes from this: https://deno.land/posts/v1.5#stricter-type-checks-in-stable
Luckily, you can override this creating a `` `tsconfig.json``` in you project with this content:

``` JSON
{
  "compilerOptions": {
    "isolatedModules": false
  }
}
```

Then, execute your code like this:

``` 
deno run -c typescript.json --allow-net --allow-read --unstable server.ts
```

Let me know if this works for you!
We have to wait for the others deps update their code. This is a temporary fix.

**Comment by tsaulic** [comment]
> It seems the issue comes from this: https://deno.land/posts/v1.5#stricter-type-checks-in-stable
> Luckily, you can override this creating a `tsconfig.json` in you project with this content:
> 
> ```json
> {
>   "compilerOptions": {
>     "isolatedModules": false
>   }
> }
> ```
> 
> Then, execute your code like this:
> 
> ```
> deno run -c tsconfig.json --allow-net --allow-read --unstable server.ts
> ```
> 
> Let me know if this works for you!
> We have to wait for the others deps update their code. This is a temporary fix.

You're a champ, this worked for me. Finally I will be able to get back to my poor coding :D Thank you!

**Comment by eveningkid** [comment]
Hey guys,

I know I'm late to the party, thanks @stillalivx for helping out really.

Have you guys actually tried to reload your dependencies? I used to get this error because of an older version of `deno_mysql` and now it's gone.

If not, try: `deno run --reload your_script_name.ts`, replacing/adding the usual flags/filename you have.

@tsaulic it really seems to be a cache issue on your google instance. Try reloading your cache there with `--reload` and that should do the trick.

Keep in touch

**Comment by trawor** [comment]
so is there a way to remove mongo deps if I do not need?

**Comment by boyarzun** [comment]
I had the same problem (-isolatedModules...), this is what helped me to understand:

**Type-Only Imports and Export**
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-exports (..._if you’ve hit issues under --isolatedModules, TypeScript’s transpileModule API, or Babel, this feature might be relevant_...)

And here is another example of how I used **export type**

```
// deps.ts

import {
    Application,
    Router,
    RouterContext
} from 'https://deno.land/x/oak/mod.ts';

export {
    Application,
    Router,
};

export type { RouterContext };
```

**Comment by TradeIdeasPhilip** [comment]
> I had the same problem (-isolatedModules...), this is what helped me to understand:
> 
> **Type-Only Imports and Export**
> https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-exports (..._if you’ve hit issues under --isolatedModules, TypeScript’s transpileModule API, or Babel, this feature might be relevant_...)
> 
> And here is another example of how I used **export type**
> 
> ...

The original question was about a standard Deno file that is causing problems.  Nothing that we can change directly.

**Comment by cuauth** [comment]
are you still having this issue?, im having it with a different project. but wanted to know if you could solved it

**Comment by stillalivx** [comment]
Well, is seems that the issue was solve at least in DenoDB with the last version. You should check if the others dependencies you are using in your project throws the error.

**Comment by cuauth** [comment]
Thanks!, i will

**Comment by eveningkid** [comment]
Hey,

I hope no one is still having issues with this.

It seems to have been fixed following @stillalivx suggestions :)

I'll close this for now.

Have a great day
