### ISSUE TITLE
Recommended Structure?

### ISSUE THREAD

**Issue by andrewc910** [eveningkid/denodb#156]
Hey, sorry this isn't an issue but I didn't find any place like a gitter or something to bring this up. 

What is the recommended structure for denodb? How should api routes go about importing the required models and database? 

If each model is in a separate file, should each model pull in the database config/connection module or should the database connection module import each model? 

To give some examples:
- Each model imports database
```js
// src/models/user
import { DataTypes, Model } from "https://deno.land/x/denodb/mod.ts";

import Database from "../database/config.ts";

class User extends Model {
  static table = "users";

  static timestamps = true;

  static fields = {
    id: {
      primaryKey: true,
      autoIncrement: true,
    },
    name: DataTypes.STRING,
    email: {
      type: DataTypes.STRING,
      allowNull: false,
      length: 50,
    },
  };
}

Database.link([User]);

export default User;

// src/database/config
import { Database as DatabaseConnection } from "https://deno.land/x/denodb/mod.ts";

const Database = new DatabaseConnection("postgres", {
  username: "",
  password: "",
  database: "",
  host: "",
});

export default Database;

// src/pages/api/user
import User from "../../models/user
```

- Database imports models
```js
// src/models/user
import { DataTypes, Model } from "https://deno.land/x/denodb/mod.ts";

class User extends Model {
  static table = "users";

  static timestamps = true;

  static fields = {
    id: {
      primaryKey: true,
      autoIncrement: true,
    },
    name: DataTypes.STRING,
    email: {
      type: DataTypes.STRING,
      allowNull: false,
      length: 50,
    },
  };
}

export default User;

// src/database/config
import { Database as DatabaseConnection } from "https://deno.land/x/denodb/mod.ts";
import User from "../models/user.ts"

const Database = new DatabaseConnection("postgres", {
  username: "",
  password: "",
  database: "",
  host: "",
});

Database.link([User]);

export { User }
export default Database;

// src/pages/api/user
import { User } from "../../database/config.ts
```

I prefer the first one but I am not sure if that would cause a unnecessary connections. However, if neither of these are the right way to go about things, please let me know what you recommend. This is my first time using any ORM in Javascript. I typically use rails as a backend.

**Comment by eveningkid** [comment]
Hi Andrew,

This is totally fine, that's a legit question :)

I would recommend an hybrid version of what you have suggested:
- Declare your models in their own file, without **linking them directly**.
- Link your models when declaring your database configuration.
- In your routes, import models from their files, not from the database configuration.

This approach will only initiate a database connection on linking.

Also, here's your second example slightly modified:
- Removed the single `User` export from `database/config.ts`.
- Changed the `User` import in `api/user.ts`

```ts
// src/models/user
import { DataTypes, Model } from "https://deno.land/x/denodb/mod.ts";

export default class User extends Model {
  static table = "users";
  static timestamps = true;
  static fields = { ... };
}

// src/database/config
import { Database as DatabaseConnection } from "https://deno.land/x/denodb/mod.ts";
import User from "../models/user.ts";

const Database = new DatabaseConnection("postgres", {
  username: "",
  password: "",
  database: "",
  host: "",
});

Database.link([User]);

export default Database;

// src/pages/api/user
import User from "../../models/user.ts";
```

I can only understand your feeling going from Rails to this, Ruby and JS are quite different in essence!

Hope this clarifies your question.

Have a great day!
