### ISSUE TITLE
MySQLConnector Error: Not supported

### ISSUE THREAD

**Issue by sluy** [eveningkid/denodb#176]
Im trying to test out denodb using same an old database for another project (with laravel). Db connection is ok and working fine; i can see it in laravel connection, phpmyadmin and adminer.

This is my code (very simple, a copy & paste of main denodb demo):

`import {
  Database,
  Model,
  DataTypes,
  MySQLConnector,
} from "https://deno.land/x/denodb/mod.ts";

const connector = new MySQLConnector({
  host: "localhost",
  username: "root",
  password: "myultrasecretpassword",
  database: "e1r2x",
  port: 3306,
});

const db = new Database({ connector, debug: true });

class Flight extends Model {
  static table = "flights";
  static timestamps = true;

  static fields = {
    id: { primaryKey: true, autoIncrement: true },
    departure: DataTypes.STRING,
    destination: DataTypes.STRING,
    flightDuration: DataTypes.FLOAT,
  };

  static defaults = {
    flightDuration: 2.5,
  };
}

db.link([Flight]);

await db.sync({ drop: true });
`

Always got this error:

`{ schema: [Function: Flight], table: "flights", type: "drop", ifExists: true }
INFO connecting 127.0.0.1:3306
INFO close connection
error: Uncaught (in promise) Error: Not supported
      throw new Error("Not supported");
            ^
    at auth (auth.ts:45:13)
    at buildAuth (auth.ts:34:24)
    at PoolConnection._connect (connection.ts:72:20)
    at async PoolConnection.connect (connection.ts:106:5)
    at async Client.createConnection (client.ts:47:5)
    at async DeferredStack.creator (pool.ts:61:20)
    at async DeferredStack.pop (deferred.ts:35:16)
    at async ConnectionPool.pop (pool.ts:93:14)
    at async Client.useConnection (client.ts:105:24)
    at async Client.execute (client.ts:96:12)`

Any help? Thanks in advance.

Edit:
Im using MySQL v8.0.22 in Ubuntu 20.04.

**Comment by w7shdev** [comment]
Hi @sluy I  ran your code and it's works fine  
Do some  of troubleshooting 
first make sure that you run this file with the right permission 
1. check database port 
2. reload the cache by using ` deno  cache -r yourfilename.ts`

and give it a try also I  recommend to import from deno.land for versioning 
e.g 
```
import {
    Database,
    Model,
    DataTypes,
    MySQLConnector,
    } from "https://deno.land/x/denodb@v1.0.21/mod.ts";
  ```

**Comment by JADSN** [comment]
DenoDB is using `deno_mysql` this this lib doesn't has support for `caching_sha2_password`

Using docker/podman with `'--default-authentication-plugin=mysql_native_password'`

```sh
podman run --name some-mysql -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=my-secret-pw mysql '--default-authentication-plugin=mysql_native_password'
``` 

It works for me

**Comment by eveningkid** [comment]
Hey,

Thanks a lot to @w7shdev and @JADSN for helping, really.

I believe João's answer might be the answer you're looking for Stefan.

I'll close the issue for now :)

Good day!
