### ISSUE TITLE
Cannot read property 'table' of undefined

### ISSUE THREAD

**Issue by RichardJd** [eveningkid/denodb#182]
After upgrading to version 1.0.21, i'm having the error below:

```bash
TypeError: Cannot read property 'table' of undefined
    at Function.create (model.ts:418:26)
    at EntryRouter.ts:21:31
    at async dispatch (middleware.ts:41:7)
    at async dispatch (middleware.ts:41:7)
    at async dispatch (middleware.ts:41:7)
    at async allowedMethods (router.ts:496:7)
    at async dispatch (middleware.ts:41:7)
    at async dispatch (middleware.ts:41:7)
    at async Application.#handleRequest (application.ts:252:9)
```

At application start, it looks like the database is connected, but apparently it’s like the table doesn’t exist.

The database is Postgres.

**Comment by eveningkid** [comment]
Hi Richard,

It's quite hard to debug without your code.

From the error message, it looks like you're missing a `.table` property on your model.
Models should follow this pattern:
```js
class Car {
  static table = 'cars'; // This is the part that seems to be missing
}
```

Let me know if this helps!

**Comment by RichardJd** [comment]
Hi Arnaud,

Sorry for not even posting the code.

The model is the way you mentioned, I didn't change anything, but I went to test it now and it worked :)

Thanks for your support!

**Comment by trydalch** [comment]
@RichardJd always good to post what resolved your issue for those in the future (I'm running into the same thing now)

**Comment by trydalch** [comment]
For me, it was that I didn't call `db.link()`
