### ISSUE TITLE
MongoClient to 0.20.1

### ISSUE THREAD

**Issue by damienmillet** [eveningkid/denodb#183]
Ty

**Comment by eveningkid** [comment]
Hey,

Dependencies will soon all be upgraded.

Next time, feel free to give it a try. It's open-sourced for a reason.

Car c'est facile de laisser tout le travail aux autres n'est ce pas :)

**Comment by damienmillet** [comment]
Peut être ne t'est il pas venu a l'idée qu'il fallait savoir le faire pour pouvoir participer, que le simple fait que ton projet soit open source ne signifie pas que tous les utilisateurs ont le même niveau de connaissance du sujet. 
Merci pour cette belle démonstration de délit d'initié sarcastique qui gangrène le monde des dev.
Ta seule qualité ici est d'avoir trouvé un nom cohérent, on est très loin de Doctrine.

Continues d'être un connard orgueilleux ça t'aidera :)

**Comment by eveningkid** [comment]
<img width="868" alt="Screenshot at Apr 19 22-48-23" src="https://user-images.githubusercontent.com/7188494/115307603-5da62000-a161-11eb-9b0c-031527e3cbc3.png">

<img width="925" alt="Damien Millet @damienmillet" title="Damien Millet @damienmillet" src="https://user-images.githubusercontent.com/7188494/115307702-83332980-a161-11eb-9afe-42a481ce9299.png">
