### ISSUE TITLE
Error: No such host is known

### ISSUE THREAD

**Issue by FSou1** [eveningkid/denodb#185]
When I use the following host:

```
const connector = new MongoDBConnector({
  uri:
    "mongodb://admin:RehlmKTm5pr9f9MG@cluster0.vsk29.mongodb.net/test?retryWrites=true&w=majority",
  database: "test",
});
```

I get the following error:

```
error: Uncaught (in promise) Error: No such host is known. (os error 11001)
    at processResponse (deno:core/core.js:223:11)
    at Object.jsonOpAsync (deno:core/core.js:240:12)
    at async Object.connect (deno:runtime/rt/30_net.js:224:13)
    at async MongoClient.connect (client.ts:20:18)
    at async MongoDBConnector._makeConnection (mongodb-connector.ts:42:7)  
    at async MongoDBConnector.query (mongodb-connector.ts:65:5)
    at async Database.query (database.ts:227:21)
    at async Function.createTable (model.ts:161:5)
    at async Database.sync (database.ts:197:7)
```

The same host is normally connected with Node.js and the `mongodb` npm package.

**Comment by eveningkid** [comment]
Hi Maxim,

This might be an error coming from `deno_mongo` which is the driver used in denodb for Mongo.

Could you see if connecting to your URI from [their documentation example](https://github.com/denodrivers/deno_mongo#examples) works for you?

If it does, then it might be a case of upgrading this driver version which I can help with.
Otherwise, this should be dealt with on their repository instead.

Let me know so we can figure this out together!

**Comment by FSou1** [comment]
Hi Arnaud,

No, it does not work (I've also created an [issue](https://github.com/denodrivers/deno_mongo/issues/168) in their repository).

**Comment by eveningkid** [comment]
Mmm, I believe most people are using their cloud service so you're right it should be supported.

For now, I will close this issue since this isn't directly related to denodb and will eventually be fixed with the driver.

If there is anything else, let me know :)

**Comment by FSou1** [comment]
Yes, you are right.

This fix should be applied to the driver side once the Deno resolveDns API becomes available.

**Comment by tavadur** [comment]
Hey,

In this comment '[mongo connect](https://github.com/denodrivers/deno_mongo/issues/172#issuecomment-770368981)'  is another solution to connect to MongoDB Atlas Cluster which is working fine, is this possible to achieve it with denodb also?

I've tried to modify _**mongodb-connectors.ts**_ but with no luck, facing below error:

`error: Uncaught (in promise) Error: MongoError: "Connection failed: MongoError: {\"ok\":0,\"errmsg\":\"bad auth : Authentication failed.\",\"code\":8000,\"codeName\":\"AtlasError\"}"throw new MongoError('Connection failed: ${e.message || e}');`
