### ISSUE TITLE
Option to use database client methods directly.

### ISSUE THREAD

**Issue by Foxford13** [eveningkid/denodb#186]
Hi,
I was wondering if there is an option, or plan to implement, to use db clients directly. Not sure if I missed it, but I could not find any direct access to db clients in the docs. Some of the methods are very useful and it would be a nice feature. I am asking in particular about mongoDBs "db.collection.aggregate". I always found it extremely useful for building complex queries and its also nice to have that extra level of control with any db in case you need it. Whether you use ORM or not.

**Comment by eveningkid** [comment]
Hi,

This is a very nice idea.

Would something like `database.getClient()` do the trick for you?
This can be added I'm sure.

Keep in touch

**Comment by Foxford13** [comment]
As long as it would allow us ot use the client as specified in the dbs docs, I think that would be absolutely perfect.

**Comment by eveningkid** [comment]
Hey,

I know it's probably too late but you can now use `database.getClient()`.

Good day :)
