### ISSUE TITLE
Breaking change in postgres driver is breaking PostgresConnector

### ISSUE THREAD

**Issue by Myssiry** [eveningkid/denodb#193]
Driver for postgres changed something, which is breaking your `PostgresConnector`.
https://github.com/denodrivers/postgres/commit/ec3d360c3db35d04a5d0bb6e7f3fadcd98c9da10
Error
![image](https://user-images.githubusercontent.com/71568768/105836856-c26c3700-5fc5-11eb-85c0-2cea20624bdb.png)

Also look at this: https://github.com/eveningkid/denodb/pull/192#issuecomment-767438638

**Comment by diblex** [comment]
I checked, and this is happening because denodrivers/ postgres updated 2 days ago to v0.5.0 introducing breaking changes. denodb is fetching the last version of this dependency so it's affected by these breaking changes.

**Comment by diblex** [comment]
Fixed in my PR https://github.com/eveningkid/denodb/pull/192

**Comment by eveningkid** [comment]
Hi Missiry,

Thanks to David this is now fixed in [1.0.22](https://github.com/eveningkid/denodb/releases/tag/v1.0.22).

This should fix your issue!

Have a great day
