### ISSUE TITLE
Decimal and UUID Data type

### ISSUE THREAD

**Issue by bander-saeed94** [eveningkid/denodb#20]
I notice these data types are available:
export const DATA_TYPES: Fields = {
  INTEGER: "integer",
  FLOAT: "float",

  BOOLEAN: "boolean",

  STRING: "string",
  TEXT: "text",

  DATETIME: "date",
  TIMESTAMP: "timestamp",
};

will Decimal and  UUID data type be added?
As well for enum.

**Comment by eveningkid** [comment]
Hey,

Thanks for asking.

I need to add more data types, you are right.
I will update this issue once it's done!

**Comment by eveningkid** [comment]
Hello again,

I added all the types you may need.

- UUID:
```typescript
id: DATA_TYPES.UUID
```
- Decimal:
```typescript
amount: DATA_TYPES.DECIMAL
// or
amount: {
  type: DATA_TYPES.DECIMAL,
  precision: 4, // optional
  scale: 2 // optional
}
```
- Enums:
```typescript
status: {
  type: DATA_TYPES.ENUM,
  values: ['active', 'canceled']
}
```

To use them, you just need to run `deno run --reload ...` and that should do it.

Hope this helps :)
