### ISSUE TITLE
There is a problem with Mongo Service?

### ISSUE THREAD

**Issue by dkaerit** [eveningkid/denodb#200]
I understand that denoDB (a great library, by the way, thanks for existing) depends on the library of [mongo@v0.20.1](https://deno.land/x/mongo@v0.20.1)

which I have seen that his CI is failing,

the problem i have is that i want to connect to my mongo atlas database via uri 

```javascript
const connection = new MongoDBConnector({
uri: `mongodb+srv://${env.USERNAME}:${env.PASSWD}@${env.CLUSTER}.z2cjr.azure.mongodb.net/${env.DATABASE}?retryWrites=true&w=majority`,
   database: env.DB
});
```

But I have errors connecting to the host... 
Before switching from deno_mongo to denodb I was having this same problem connecting via that format, so I deduce that errors are creeping from that dependency. Or not, I don't know. Maybe I'm doing something wrong. Any ideas?

**Comment by eveningkid** [comment]
Hi Diego,

I appreciate the kind words, thank you!

`denodb` is using `deno_mongo` under-the-hood so it won't be working either...we're limited by the driver at the moment.

This is however something you could ask on their repo. I think there was a similar issue recently, with this kind of URL.

Have a look at `deno_mongo` issues, I'm sure you're not the only one :)

**Comment by dkaerit** [comment]
Thanks to you.  And yes, I had been looking at his repository yesterday, and apparently everything leads to it being deno_mongo's error.  I'll close the issue around here then.

**Comment by borsemayur2** [comment]
I'm able to connect to atlas with following config. Can we pass it to MongoConnector?

```
await client.connect({
    db:'<db>',
    tls:true,
    servers: [
        {
            host: 'cluster0-shard-00-02.soz4m.mongodb.net',
            port: 27017
        }
    ],
    credential: {
        username:"<username>",
        password: '<pwd>',
        db: '<db>',
        mechanism:'SCRAM-SHA-1'
    }
})
```

**Comment by borsemayur2** [comment]
@dkaerit Following code worked for me for `denodb@v.1.0.35`

```
import { Database, MongoDBConnector } from 'https://deno.land/x/denodb/mod.ts';

const connector = new MongoDBConnector({
  database: '<db>',
  db:'<db>',
    tls:true,
    servers: [
        {
            host: 'cluster0-shard-00-02.soz4m.mongodb.net',
            port: 27017
        }
    ],
    credential: {
        username:"<username>",
        password: '<pwd>',
        db: '<db>',
        mechanism:'SCRAM-SHA-1'
    }
});

const db = new Database(connector);


```
