### ISSUE TITLE
Deno DB Truncate

### ISSUE THREAD

**Issue by duqrlgkdntm9** [eveningkid/denodb#206]
Hello Use Deno DB Thanks

Deno DB There's a drop.

Where Truncate??

I want to reset the database data.

Thanks

**Comment by Deel96** [comment]
Is   await db.sync({ drop: true }); working for you?

When I have 2 tables and one has a foreign key I get : Uncaught (in promise) Error: Cannot delete or update a parent row: a foreign key constraint fails
      throw new Error(error.message);
      
      When drop is set to true

**Comment by duqrlgkdntm9** [comment]
> Is `await db.sync({ drop: true }); `working for you?
> 
> When I have 2 tables and one has a foreign key I get :
> 
> ```
> Uncaught (in promise) Error: Cannot delete or update a parent row: a foreign key constraint fails
>       throw new Error(error.message);
> ```
> 
> When drop is set to true

db.sync({ drop: true }) is drop function?
Isn't it a function to remove the table?

I want to initialize the record.
Is there no Truncate function?

**Comment by stillalivx** [comment]
@Deel96, what db engine you're using?

**Comment by stillalivx** [comment]
@duqrlgkdntm9, unfortunately there isn't a truncate function. Just to be sure, you want to use something like:
```typescript
TableName.truncate();
```
Right?

**Comment by eveningkid** [comment]
I think @duqrlgkdntm9 is probably looking for two things:

```js
await db.sync({ truncate: true });
// and
Model.truncate();
```

If `Model.truncate()` is added, I'm pretty sure it would be very simple to then have it in the `sync(...)` method.
It would just need to call `.truncate()` on every linked model.

This would definitely be good to have...!

**Comment by stillalivx** [comment]
Hey! @eveningkid, I checked some docs and I realised that knex doesn't has something like truncateIfExists... So, if Mode.truncate() is use and x table is not created, database will throw errors. Should we continue with  db.sync({ truncate: true })? 

That is the only problem, If the tables were created, db.sync({ truncate: true }) works perfectly!

I already have the code tested on SQLite and MySQL waiting for green light for PR! :)

**Comment by eveningkid** [comment]
Well, I think it's fine since if a user sets `truncate` to true, then they assume the tables exist.

If there is no way to know if they exist beforehand, errors should be expected either way :)

All good @stillalivx!

**Comment by eveningkid** [comment]
Since it's been added with #230, you should now be able to truncate your tables by default:

```js
await db.sync({ truncate: true });

// or one by one

await Model.truncate();
```

Remember to use denodb latest version or `v1.0.28` at least.

Thank you for @stillalivx's efforts, great addition :)

Good day!
