### ISSUE TITLE
Foreign key constraint is incorrectly formed: Wrong order of linking entities with foreign keys

### ISSUE THREAD

**Issue by Deel96** [eveningkid/denodb#207]
Using the code from: https://eveningkid.com/denodb-docs/docs/guides/foreign-key

gets me the error:
error: Uncaught (in promise) Error: Can't create table `test`.`businesses` (errno: 150 "Foreign key constraint is incorrectly formed")
      throw new Error(error.message);

db.link([Business, Owner]);
has to be 
db.link([Owner, Business]);

then it works.

**Comment by eveningkid** [comment]
Hey,

Sorry for the trouble, you are right.

@stillalivx took care of it in eveningkid/denodb-documentation#3 and the change should be made soon enough in the docs.

I will close this for now :)

Have a great day
