### ISSUE TITLE
Dependent package "dex" not found

### ISSUE THREAD

**Issue by takxlz** [eveningkid/denodb#209]
I get an error that the dependent package "dex" cannot be found.

The following is a part of the log when an error occurs.

error: Import 'https://raw.githubusercontent.com/denjucks/dex/master/mod.ts' failed: 404 Not Found
    at https://deno.land/x/denodb@v1.0.23/deps.ts:3:0

Thanks.

**Comment by takxlz** [comment]
Did the dex repository move to "https://github.com/aghussb/dex"?
As an experiment, I forked denodb and changed the dex url in deps.ts to the above repository and it worked.

**Comment by magician20** [comment]
I have the same problem 
(error: Import 'https://raw.githubusercontent.com/denjucks/dex/master/mod.ts' failed: 404 Not Found
 at https://deno.land/x/denodb@v1.0.23/deps.ts:3:0)
any solution ?

**Comment by magician20** [comment]
I tried (forked denodb solution ) and i'm still getting same error.

**Comment by takxlz** [comment]
@magician20 Hmm, The old deno cache may have an effect. Try clearing the cache.

**Comment by magician20** [comment]
@takxlz Same error happen even if I clean or delete the cache.
should I use different 3d.Lib ?

**Comment by yeop-sang** [comment]
Can I fix this problem on my computer?
I don't have idea to fix without forking this project to my github.

**Comment by fnuttens** [comment]
@takxlz I confirm that it works by changing the dex URL to https://raw.githubusercontent.com/aghussb/dex/master/mod.ts.

**Comment by eveningkid** [comment]
Hey guys,

I was totally not looking after the repo, so very sorry this has been going on for days!

I just [committed to master](https://github.com/eveningkid/denodb/commit/7bf060c14f4b0ac33a13de219e7b25afb5531d5f) with a fix in the dependency file.

If there is anyone that can just fetch the library again and make sure this works, that would really help take this forward :)

Thanks again for helping out, really.

Have a great day

**Comment by fnuttens** [comment]
@eveningkid anytime! And master works now too :)

**Comment by fnuttens** [comment]
@eveningkid même après des années, je ne me lasse pas de cette ville 🥨
Bonne soirée à toi et félicitations pour ton bel ORM ;)
