### ISSUE TITLE
TS2551 [ERROR]: Property 'integer' does not exist on type 'Fields'. Did you mean 'INTEGER'? 

### ISSUE THREAD

**Issue by borsemayur2** [eveningkid/denodb#219]
```
// Works
name: DataTypes.string(25),  
_age: { type: DataTypes.INTEGER, length: 2 }, 

// Throws error
age: DataTypes.integer(2),
```

Versions:
denodb: v1.0.26
deno: 1.8.3

**Comment by stillalivx** [comment]
It looks like there is not a shortcot for ```DataTypes.INTEGER```. 
In [docs](https://eveningkid.com/denodb-docs/docs/api/field-descriptors) just exist string, enum, and decimal. 

@eveningkid should we add this shortcut?

**Comment by eveningkid** [comment]
Hey @stillalivx, it's been a while :)

Yes this would be a great idea.
It could be added on this file, by applying the same logic with `integer(...)`.

Feel free to PR, I'll merge it right away!

**Comment by stillalivx** [comment]
@eveningkid. Okay, on my way!

**Comment by eveningkid** [comment]
The shortcut has been added thanks to @stillalivx :)

You can now use `age: DataTypes.integer(2)` in your fields!

Good day

**Comment by borsemayur2** [comment]
@eveningkid @stillalivx Great. Thanks.
