### ISSUE TITLE
MariaDB Setup on Doc

### ISSUE THREAD

**Issue by Gumichocopengin8** [eveningkid/denodb#221]
Hello, thanks for the great tool.
There's no description about how to connect to MariaDB on doc https://eveningkid.com/denodb-docs/docs/getting-started
Does that mean it's same as MySQL? If so, that would be helpful to mention that somewhere on doc. 
Thanks

**Comment by eveningkid** [comment]
Hey Keita,

You're right, it is just like MySQL. Someone actually wrote [a small article about it](https://developerm.dev/2021/02/16/mariadb-connection-using-orm-in-deno).

I'm actually very unfamiliar with MariaDB myself.
If you want to contribute, it's simple: add a page like [this one](https://github.com/eveningkid/denodb-documentation/blob/main/guides/using-mysql.md) for Maria, and add a link to it [to the list here](https://github.com/eveningkid/denodb-documentation/blob/main/guides/connect-database.md).

MariaDB is supported by deno_mysql, juste like what it says on the MySQL page.

Would be really great to get your help on this :)

Let me know!

**Comment by Gumichocopengin8** [comment]
Seems like @stillalivx  added MariaDB  doc. Thanks.

**Comment by eveningkid** [comment]
Hey,

I'm just wondering what a default configuration looks like since I don't use MariaDB.

Could you please let me know if the connection looks similar to this example:

```js
const connector = new MySQLConnector({
  database: 'my-database',
  host: 'url-to-db.com',
  username: 'username',
  password: 'password',
  port: 3306, // optional
});
```

Thanks :)

**Comment by Gumichocopengin8** [comment]
I think it looks good to me. 
I'm not sure denodb supports `connectionLimit` option like [this](https://mariadb.com/kb/en/getting-started-with-the-nodejs-connector/) tho. However, anything else seems fine.

**Comment by eveningkid** [comment]
Great, thanks.

It's been added [to the docs](https://eveningkid.com/denodb-docs/docs/guides/using-mariadb.html).

Good day!

**Comment by Gumichocopengin8** [comment]
Thanks! you too!
