### ISSUE TITLE
Support the Data Mapper model

### ISSUE THREAD

**Issue by acrodrig** [eveningkid/denodb#222]
One nice thing about the TypeORM project is that it does not force you to select between the Active Record or the Data Mapper pattern. See [documentation](https://typeorm.io/#/active-record-data-mapper/what-is-the-data-mapper-pattern) about the pros/cons. 

I like the mapper model because it does not pollute my classes with annotations/subclasses.

Can DenoDB support this model as well?

Thanks for a great library.

**Comment by eveningkid** [comment]
Hey Andres,

Just had a look at this pattern and I'm not sure I entirely see why this isn't feasible already:

```js
// repository.ts
import User from "./models/user.ts";

export default {
  createAndSave(firstName: string, lastName: string) {
    const user = new User();
    user.firstName = firstName;
    user.lastName = lastName;
    return user.save();
  },
  findByName(firstName: string, lastName: string) {
    return User.where({ firstName, lastName }).first();
  },
};

// app.ts
import Repository from "./repository.ts";

const user = await Repository.createAndSave("Andres", "Rodriguez");
const row = await Repository.findByName("Andres", "Rodriguez");
```

Maybe I'm missing something here?
Or is it that denodb doesn't have a "pattern" for this that is your concern?

Let me know :)

**Comment by eveningkid** [comment]
Hey Andres,

I will close this for now since I believe it is possible with denodb.

If it isn't, really don't hesitate to comment below and I'll reopen the issue :)

Good day
