### ISSUE TITLE
Add comment for mysql column

### ISSUE THREAD

**Issue by youngyou** [eveningkid/denodb#224]
I tried generate mysql table with `Model`, but it doesn't support add comment for mysql columns.

**Comment by eveningkid** [comment]
Fixed with #225 :)

**Comment by youngyou** [comment]
There seems to be an error in this feature. The sql will be wrong when there is a `;` in `comment` property.
I have found the reason and need some time to test it.
So, do not use `;` in `comment` before fix.

**Comment by youngyou** [comment]
> There seems to be an error in this feature. The sql will be wrong when there is a `;` in `comment` property.
> I have found the reason and need some time to test it.
> So, do not use `;` in `comment` before fix.

Fixed in 2dc5ad9c26001ee63475b1c74f8d0c9310f581b7
