### ISSUE TITLE
[v1.0.30] Code breaks after upgrade from v1.0.26

### ISSUE THREAD

**Issue by borsemayur2** [eveningkid/denodb#233]
Code [repo](https://github.com/borsemayur2/users-demo-oak-graphql-server) working on `v1.0.26` breaks on `v1.0.30` with following error.

```bash
error: TS2322 [ERROR]: Type 'typeof User' is not assignable to type 'typeof Model'.
  Types of property 'pivot' are incompatible.
    Type 'import("https://deno.land/x/denodb@v1.0.27/lib/model.ts").ModelPivotModels' is not assignable to type 'import("https://deno.land/x/denodb@v1.0.26/lib/model.ts").ModelPivotModels'.
      Index signatures are incompatible.
        Type 'typeof import("https://deno.land/x/denodb@v1.0.27/lib/model-pivot.ts").PivotModel' is not assignable to type 'typeof import("https://deno.land/x/denodb@v1.0.26/lib/model-pivot.ts").PivotModel'.
          Types of property '_pivotsModels' are incompatible.
            Type '{ [modelName: string]: typeof import("https://deno.land/x/denodb@v1.0.27/lib/model.ts").Model; }' is not assignable to type '{ [modelName: string]: typeof import("https://deno.land/x/denodb@v1.0.26/lib/model.ts").Model; }'.
              Index signatures are incompatible.
                Type 'typeof import("https://deno.land/x/denodb@v1.0.27/lib/model.ts").Model' is not assignable to type 'typeof import("https://deno.land/x/denodb@v1.0.26/lib/model.ts").Model'.
                  Types of property 'fields' are incompatible.
                    Type 'import("https://deno.land/x/denodb@v1.0.27/lib/model.ts").ModelFields' is not assignable to type 'import("https://deno.land/x/denodb@v1.0.26/lib/model.ts").ModelFields'.
                      Index signatures are incompatible.
                        Type 'import("https://deno.land/x/denodb@v1.0.27/lib/data-types.ts").FieldType' is not assignable to type 'import("https://deno.land/x/denodb@v1.0.26/lib/data-types.ts").FieldType'.
                          Type 'FieldProps' is not assignable to type 'FieldType'.
db.link([User]);
         ~~~~
    at file:///home/mb/my/career/deno/denodb/min-repo/src/models.ts:21:10
```

**Comment by borsemayur2** [comment]
The issue seems with `v1.0.27` release.

**Comment by eveningkid** [comment]
Hey,

Have you changed the models file?

I don't see why you would have this error if the code is similar to the repo you gave us.

Let me know

**Comment by borsemayur2** [comment]
No.  The code works with `v1.0.26` and throws mentioned error for `v1.0.27` onwards.

**Comment by eveningkid** [comment]
Mmm, I don't get this error when I run your repo.

Could it be your Deno version? I'm out of answers on this one.

Can you try to create another tiny project, just using the denodb part from [`db.ts`](https://github.com/borsemayur2/users-demo-oak-graphql-server/blob/main/src/db.ts) and [`models.ts`](https://github.com/borsemayur2/users-demo-oak-graphql-server/blob/main/src/models.ts)?

Also try using the current version of denodb (you could even remove the version to get one from `master`).

Please, just let me know if this clean start works for you. We'll find what's causing the issue :)

**Comment by borsemayur2** [comment]
The issue was with module cache. I used `reload: true` in `scripts.yaml` to fetch all modules  and its working now with `v1.0.33`. Thanks

**Comment by eveningkid** [comment]
I started to think I was going crazy!

Great to know it's all working now, Mayur.

Good day :)
