### ISSUE TITLE
Deno 1.9.2 error: TS2315 [ERROR]: Type 'Conn' is not generic. at https://deno.land/x/postgres@v0.11.1/connection/connection.ts:149:11

### ISSUE THREAD

**Issue by vmasdani** [eveningkid/denodb#249]
hi. I'm trying to import the library with this code 
```ts
import { DataTypes, Database, Model } from 'https://deno.land/x/denodb@v1.0.35/mod.ts';
```
and I got this error
```sh
Check file:///home/valianmasdani/codes/deno/denodblike/main.ts
error: TS2315 [ERROR]: Type 'Conn' is not generic.
  #conn!: Deno.Conn<Deno.NetAddr>;
          ~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/postgres@v0.11.1/connection/connection.ts:149:11
```

With Deno version:
```
deno 1.9.2 (release, x86_64-unknown-linux-gnu)
v8 9.1.269.5
typescript 4.2.2
```

DenoDB v1.0.33 works fine though. Are there any news about incompatibility issues lately in the new deno version?

**Comment by eveningkid** [comment]
Hey Muhammad,

Yes, this is a known issue and related to denodrivers/postgres#281.
We're still waiting on them to patch this issue.

Another way out was apparently to downgrade the dependency but I think a fix will come soon enough.

Let's wait and see :)

**Comment by vmasdani** [comment]
> Hey Muhammad,
> 
> Yes, this is a known issue and related to [denodrivers/postgres#281](https://github.com/denodrivers/postgres/issues/281).
> We're still waiting on them to patch this issue.
> 
> Another way out was apparently to downgrade the dependency but I think a fix will come soon enough.
> 
> Let's wait and see :)

Ah if it's from postgres we can't really do much, I guess we'll just wait

**Comment by eveningkid** [comment]
Hey Muhammad,

I just pushed to `master` an upgrade that should fix the issue.

Please let me know if you're still seeing this error using the latest version!

Thank you

**Comment by OdilonDamasceno** [comment]
@eveningkid in the file [deps.ts](https://deno.land/x/denodb@v1.0.35/deps.ts) continues in version `0.11.1`

**Comment by vmasdani** [comment]
> > Hey Muhammad,
> > Yes, this is a known issue and related to [denodrivers/postgres#281](https://github.com/denodrivers/postgres/issues/281).
> > We're still waiting on them to patch this issue.
> > Another way out was apparently to downgrade the dependency but I think a fix will come soon enough.
> > Let's wait and see :)
> 
> Ah if it's from postgres we can't really do much, I guess we'll just wait

I'm using https://github.com/eveningkid/denodb/commit/9a19bdb22ec2791aa7921f23c6206759ac2e2d0d and it works fine now 😄 

![Screenshot from 2021-04-29 15-46-59](https://user-images.githubusercontent.com/37009464/116525004-45bd6180-a902-11eb-9373-c59a62842ca5.png)
![Screenshot from 2021-04-29 15-48-21](https://user-images.githubusercontent.com/37009464/116525070-5b328b80-a902-11eb-92dd-3fd73be58aa5.png)

**Comment by eveningkid** [comment]
@OdilonDamasceno yes that is because deno.land picks up on every new github release, not on `master` I think :)

I was waiting on @vmasdani to check if the issue was solved first, before creating a new release.

So it's now out with `1.0.36`, thank you for your help!

Have a great day
