### ISSUE TITLE
Deploing at fly.io - ' has no exported member 'open'.

### ISSUE THREAD

**Issue by adahox** [eveningkid/denodb#25]
Hey guys,

i'm trying deploy my app on fly.io and 

`[builder] error: TS2305 [ERROR]: Modu
le '"../sqlite/mod"' has no exported member 'open'.
[builder]   open as openSQLiteFile,
[builder]   ~~~~
[builder]     at https://deno.land/x/denodb/deps.ts
[0m:12:3
[builder]
[builder] TS2305 [ERROR]: Module '"../sqlite/mod"' has
 no exported member 'save'.
[builder]   save as saveSQLiteFile,
[builder]   ~~~~
[builder]     at https://deno.land/x/denodb/deps.ts
[0m:13:3
[builder] 
[builder] Found 2 errors.
[builder] ERROR: failed to build: exit status 1
Error failed with status code: 7`

it's strange because I deployed my app 05/22 and everything works fine. Today starts this error.

as I see, the dependency deno-sqlite has updated today. could be it the reason  once the sqlite/mod has no exported 'save' ?

**Comment by eveningkid** [comment]
Hey Adão,

Sorry for the inconvenience!

Yes you are right, it was because of the new SQLite version. It is now fixed, I tried it on my end.

If you're still facing an issue, feel free to reopen the issue :)

Have a good day!
