### ISSUE TITLE
Question: Multiple relationships to one table

### ISSUE THREAD

**Issue by Develeon64** [eveningkid/denodb#263]
Hello there,
I didn't find a way to have multiple fields of one table point to different datasets of the same other table.

Like:
Members
    - id: number (primary key)
    - name: string
Actions
    - id: number (primary key)
    - description: string
    - author: number (foreign key: Members.id)
    - for_member: number (foreign key: Members.id)
    
Is this possible with DenoDB and how do I achieve this?
Thanks for your help in advance!

Develeon

**Comment by CastelloDev** [comment]
@Develeon64  Found this by scanning through the repo: https://github.com/eveningkid/denodb/blob/master/lib/relationships.ts
Looks like there's another field on the belongsTo method that allows you to pass through options for the primaryKey and foreignKey field names

**Comment by Develeon64** [comment]
Thanks @CastelloDev! I looked at it and just tried it out. And this really works, just define an object containing `foreignKey: <column name>`.
Thanks for your help!

Develeon
