### ISSUE TITLE
how to properly handle errors with sqlite?

### ISSUE THREAD

**Issue by chovy** [eveningkid/denodb#282]
I have a unique constraint on a table (email) and I need to know if the email already exists.

I could look it up first, but is there a proper way to handle errors and return an error response with denodb?

**Comment by schuelermine** [comment]
I don’t know if it qualified as “proper”, but you could make a transaction and use `Promise.prototype.catch()`.
You could also just use a try/catch block.

**Comment by eveningkid** [comment]
Hi,

As stated above by @schuelermine, try/catch should be just fine:

```js
try {
  const user = await User.find({ email: ... }).get();
} catch (error) {
  ...
}
```

If for whatever reason this is not working, please update us on this and I'll reopen this issue :)

Have a great day
