### ISSUE TITLE
Can't sync many to many relation

### ISSUE THREAD

**Issue by DavidBonelo** [eveningkid/denodb#290]
Hi, I was following the examples on the documentation, but the example of many to many relations didn't work.
I got this error
> error: Uncaught (in promise) Error: Can't create table \`test\`.\`businesses_owners` (errno: 150 "Foreign key constraint is incorrectly formed")

The doc says that It is a good practice to put the pivot models first
`db.link([BusinessOwner, Business, Owner]);`
But in the database It seems like it starts crating the pivot table first and fails to create the foreign keys.

So I changed the order and put the pivot table at the end.
`db.link([Business, Owner, BusinessOwner]);`
And It worked, but only the first sync() the second time I get this error:
> error: Uncaught (in promise) Error: Multiple primary key defined

If I always use sync({drop: true}) I don't get any error, but I can't keep the data.

This is the code:
```ts
import { db } from "./connector.ts";
import {
  DataTypes,
  Model,
  Relationships,
} from "https://deno.land/x/denodb@v1.0.38/mod.ts";

class Owner extends Model {
  static table = "owners";

  static fields = {
    id: {
      type: DataTypes.STRING,
      primaryKey: true,
    },
    name: DataTypes.STRING,
  };

  static businesses() {
    return this.hasMany(Business);
  }
}

class Business extends Model {
  static table = "businesses";

  static fields = {
    id: {
      type: DataTypes.STRING,
      primaryKey: true,
    },
    name: DataTypes.STRING,
  };

  static owners() {
    return this.hasMany(Owner);
  }
}
const BusinessOwner = Relationships.manyToMany(Business, Owner);

// db.link([BusinessOwner, Business, Owner]);
// ! error: Uncaught (in promise) Error: Can't create table `test`.`businesses_owners` (errno: 150 "Foreign key constraint is incorrectly formed")

db.link([Business, Owner, BusinessOwner]);
// ! error: Uncaught (in promise) Error: Multiple primary key defined

await db.sync();
// await db.sync({ drop: true });

await db.close();
```
Am I doing something wrong 🤔? can someone replicate the error?

> denodb 1.0.38
mysql  Ver 15.1 Distrib 10.5.11-MariaDB, for Linux (x86_64) using  EditLine wrapper
deno 1.12.1 (release, x86_64-unknown-linux-gnu)
v8 9.2.230.14
typescript 4.3.5

**Comment by DavidBonelo** [comment]
🤔 If I don't use `sync()` every time I run my program, I don't get any errors, is this how it's supposed to be?

The doc says:
> Synchronizing your models means making sure your models are available in the provided database. If they do not exist, synchronizing will create them.

That makes me think that I should use `sync()` every time my program starts.

**Comment by matthewp** [comment]
If you look at the code it try to create the tables every time you use sync, so yeah it won't worked without either drop: true or truncate: true. This works ok in development but clearly you don't want to erase your data in production so you shouldn't use sync there.

The name is confusing because you are expecting it to like some how add new columns that were added to an existing table, etc, but it doesn't do that. So my recommendation is get your models as close to how you want them during development and not use sync in production. Then when you do add columns do it with a migration sql script rather than depending on denodb to do it, because it doesn't do migrations.

**Comment by DavidBonelo** [comment]
OK, thank you for your explanation.

just to clarify, the pivot table should be put **last** in the list, right?

**Comment by matthewp** [comment]
@DavidBonelo I'm just a user and not a maintainer of this library, but this matches my experience.
