### ISSUE TITLE
Issue with passing Models[] into .link() method.

### ISSUE THREAD

**Issue by TokenChingy** [eveningkid/denodb#3]
So I have a situation here where I have a function for dynamically importing models into an array to then be linked to the database instance. I'm getting this error:

```error: TS2345 [ERROR]: Argument of type 'Model[]' is not assignable to parameter of type '(typeof Model)[]'.
  Type 'Model' is missing the following properties from type 'typeof Model': prototype, table, timestamps, fields, and 30 more.
database.link(await getModels("./models"));
```

So my function for dynamically importing is:

```
import { Model } from "https://deno.land/x/denodb/mod.ts";
import { walk } from "https://deno.land/std/fs/walk.ts";

const getModels = async (path: string): Promise<Model[]> => {
  const models: Model[] = [];

  for await (const file of walk(path)) {
    if (file.isFile) {
      const module = await import(`./${file.path}`);
      models.push(module.default);
    }
  }

  return Promise.resolve(models);
};
```

and the call to link is:

```
database.link(await getModels("./models"));
```

I did try:

```
const models: Model[] = await getModels("./models");
database.link(models);
```

but that had the same error.

I suspect it's to do with the link method requiring `models` to be of `(typeof Model)[]` which is `function`. But I can't seem to get it to work.

**Comment by eveningkid** [comment]
Hey Jason,

So I think you're right, the problem seems that you're trying to convert `Model[]` to `typeof Model[]` which is not the same.

`Model[]` means a list of **instances** of `Model`. However, when you define a model, it's actually a class with static attributes, not an instance of that model.

What you could try to do is to replace:
```typescript
const models: Model[] = [];
```
With:
```typescript
const models: typeof Model[] = [];
```

I will create a more specific type for that, like ` type ModelSchema = typeof Model`.
I hope this does the trick for you! Let me know if it doesn't.

Thanks for using DenoDB and giving me some feedback :)

**Comment by TokenChingy** [comment]
Oh yea, that makes a lot of sense now. Got it, that got it working sort of. I've now encountered this error:

```
error: Uncaught TypeError: table[type] is not a function
      instruction = table[type](...fieldNameArgs);
                               ^
    at addFieldToSchema (https://deno.land/x/denodb/lib/helpers/fields.ts:30:32)
    at TableBuilder._fn (https://deno.land/x/denodb/lib/model-initializer.ts:39:13)
    at TableBuilder.toSQL (https://deno.land/x/dex/lib/schema/tablebuilder.js:45:12)
    at SchemaCompiler_PG.createTable (https://deno.land/x/dex/lib/schema/compiler.js:89:25)
    at SchemaCompiler_PG.toSQL (https://deno.land/x/dex/lib/schema/compiler.js:72:26)
    at SchemaBuilder.toSQL (https://deno.land/x/dex/lib/schema/builder.js:81:43)
    at SchemaBuilder.Target.toQuery (https://deno.land/x/dex/lib/interface.js:9:21)
    at SchemaBuilder.toString (https://deno.land/x/dex/lib/schema/builder.js:77:15)
    at ModelInitializer.init (https://deno.land/x/denodb/lib/model-initializer.ts:54:9)
    at async Function._createInDatabase (https://deno.land/x/denodb/lib/model.ts:68:5)
```

**Comment by TokenChingy** [comment]
Actually never mind, I was using `DATA_TYPE.string` and not `DATA_TYPES.STRING`. Could you possibly make the documentation better? I'm having to dig into the source code to get answers.

**Comment by eveningkid** [comment]
I made an update with 714a04dad7796b53df0a2c80f41446f177b438f9.
For the second issue, it seems to be related to your model fields types.

I spend as much time as I can on my free time for this.
So you're obviously very welcome to contribute! Would be really great :)

**Comment by eveningkid** [comment]
Also, just added another commit (5d4b631d877eb6c960bc669939752756a8da1e35) that should bring some hints this time when you type `DATA_TYPES.something`.

If you reload the library, you should get the update!
