### ISSUE TITLE
Have you considered replacing the address of ‘raw.githubusercontent.com’? This address is not accessible in some areas

### ISSUE THREAD

**Issue by rashagu** [eveningkid/denodb#309]
`
error: error sending request for url (https://raw.githubusercontent.com/denjucks/dex/master/mod.ts): error trying to connect
`

**Comment by Galrin** [comment]
same

**Comment by Zhomart** [comment]
yes, it's gone. See https://github.com/eveningkid/denodb/issues/310#issuecomment-987962523 for a workaround

**Comment by eveningkid** [comment]
This should be fixed with #307!

Please upgrade to `master` or `1.0.40`.

Have a great day :)
