### ISSUE TITLE
Creating records with null fields

### ISSUE THREAD

**Issue by gcq** [eveningkid/denodb#34]
I'm trying to insert a new record with some null fields.

I have this model:

```typescript
class User extends Model {
  static table = "users";

  static timestamps = true;

  static fields = {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
    },
    first_name: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    last_name: {
      type: DataTypes.STRING,
      allowNull: true,
    },
    username: {
      type: DataTypes.STRING,
      allowNull: true,
    },
  };
}
```

And when trying to insert with this snippet:
```typescript
let o = {
  id: from.id,
  first_name: from.first_name,
  last_name: from.last_name ? from.last_name : null,
  username: from.username ? from.username : null
};

await User.create(o);
```

I get this error:
```
error: TS2345 [ERROR]: Argument of type '{ id: number; first_name: string; last_name: string | null; username: string | null; }' is not assignable to parameter of type 'Values | Values[]'.
  Type '{ id: number; first_name: string; last_name: string | null; username: string | null; }' is not assignable to type 'Values'.
    Property 'last_name' is incompatible with index signature.
      Type 'string | null' is not assignable to type 'FieldValue'.
        Type 'null' is not assignable to type 'FieldValue'.
      await User.create(o);
```

How can I insert a new record with null fields? Thank you!

I'm kinda new to TypeScript so apologies in advance if this is not an issue with your lib.

**Comment by eveningkid** [comment]
Hey Guillem,

Well, you must be the first one to use denodb with null values, that's all hehe!

So long story short, a value could previously only be of the following types: `number | string | boolean | Date`. So yes, `null` would throw an error!

I will update this right away :)

**Comment by eveningkid** [comment]
It should now be functional Guillem.

Just remember to run `deno run --reload ...` to get the latest version of denodb.

If you're still encountering a problem, please reopen this issue!

Have a nice day :)
