### ISSUE TITLE
Order by multiple columns not working as expected

### ISSUE THREAD

**Issue by Coteh** [eveningkid/denodb#36]
I'd like to be able to sort my select results by multiple columns. After attempting to use `orderBy` model method and [taking a quick glance in the code](https://github.com/eveningkid/denodb/blob/8eca58d4f2eeec9755c03e49de8e84083be13301/lib/translators/sql-translator.ts#L47-L52) it seems like it's only somewhat possible by stacking together `orderBy` calls. After doing this, I get inconsistent results:

*Using denodb model*
```
import { DataTypes, Database, Model } from "https://deno.land/x/denodb/mod.ts";

const db = new Database("sqlite3", {
  filepath: "temp.sqlite",
});

class Flight extends Model {
  static table = "flights";
  static timestamps = true;

  static fields = {
    id: {
      primaryKey: true,
      autoIncrement: true,
    },
    departure: DataTypes.STRING,
    destination: DataTypes.STRING,
    flightDuration: DataTypes.FLOAT,
  };

  static defaults = {
    flightDuration: 2.5,
  };
}

db.link([Flight]);

await db.sync({ drop: true });

await Flight.create([
  {
    departure: "Paris",
    destination: "Tokyo",
  },
  {
    departure: "London",
    destination: "San Francisco",
  },
  {
    departure: "Toronto",
    destination: "Montreal",
  },
  {
    departure: "London",
    destination: "New York",
  },
]);

console.log(await Flight.select("*").orderBy("departure", "asc").orderBy("destination", "asc").get());
```
Output:
```
[
  {
      id: 3,
      departure: "Toronto",
      destination: "Montreal",
      flightDuration: 2.5,
      created_at: "2020-06-05 20:01:58",
      updated_at: "2020-06-05 20:01:58"
    },
  {
      id: 4,
      departure: "London",
      destination: "New York",
      flightDuration: 2.5,
      created_at: "2020-06-05 20:01:58",
      updated_at: "2020-06-05 20:01:58"
    },
  {
      id: 2,
      departure: "London",
      destination: "San Francisco",
      flightDuration: 2.5,
      created_at: "2020-06-05 20:01:58",
      updated_at: "2020-06-05 20:01:58"
    },
  {
      id: 1,
      departure: "Paris",
      destination: "Tokyo",
      flightDuration: 2.5,
      created_at: "2020-06-05 20:01:58",
      updated_at: "2020-06-05 20:01:58"
 ]
```

*Using SQL query*
```
select * from flights
order by departure asc, destination asc;
```
Output
| id | departure | destination   | flightDuration | created_at          | updated_at          |
|----|-----------|---------------|----------------|---------------------|---------------------|
|  4 | London    | New York      |            2.5 | 2020-06-05 20:01:58 | 2020-06-05 20:01:58 |
|  2 | London    | San Francisco |            2.5 | 2020-06-05 20:01:58 | 2020-06-05 20:01:58 |
|  1 | Paris     | Tokyo         |            2.5 | 2020-06-05 20:01:58 | 2020-06-05 20:01:58 |
|  3 | Toronto   | Montreal      |            2.5 | 2020-06-05 20:01:58 | 2020-06-05 20:01:58 |

I have not tested with Postgres and MySQL, and I quickly glanced at dex's code and it doesn't seem like they make use of multiple column ordering either.

In my web app, I can work around this by sorting by one column for now. But it would be nice to have this sort of capability in the future if it's possible. Thanks.

**Comment by eveningkid** [comment]
Hey James,

You are entirely right about this, it isn't working. The way I did it was replacing the `ORDER BY` clause any time you were stacking them, i.e. that the following...

```typescript
await Flight.orderBy('a', 'desc').orderBy('b', 'desc').all();
```

...would only order by `b` and forget about `a`!

I am working on it right now. Here is the syntax I'm adding:

```typescript
// Working but not ideal
await Flight.orderBy('a', 'desc').orderBy('b', 'desc').all();

// Better
await Flight.orderBy({ a: 'desc', b: 'desc' }).all();
```

Will update this issue as soon as it's merged :)

**Comment by eveningkid** [comment]
It's been added, don't forget to reload and that should be working now!

Do not hesitate to reopen if it's not (but I swear it should hehe).

Thanks again for all the feedback James, it's very helping :)
