### ISSUE TITLE
hash module break!

### ISSUE THREAD

**Issue by VivoCyber** [eveningkid/denodb#365]
error: Module not found "https://deno.land/std/hash/mod.ts".
    at https://deno.land/x/god_crypto@v0.2.0/src/eme_oaep.ts:1:28

**Comment by allwqre** [comment]
For the time being you could use this repo as the dependency. Just replace your dependency url with `https://raw.githubusercontent.com/eveningkid/denodb/master/mod.ts`. Or, if you want a fixed version, replace `master` with a commit hash.

**Comment by VivoCyber** [comment]
ok thanks

**Comment by KnorpelSenf** [comment]
How long are you planning on leaving your nurse recent release in a broken state?

In other words, what prevents you from doing a patch release?
