### ISSUE TITLE
How to set logging?

### ISSUE THREAD

**Issue by LauraWebdev** [eveningkid/denodb#374]
Hey there,

I'm trying to setup the logger so it does not display these logs. I've seen a LoggerConfig reference in the MySQLConnector but no documentation, what are the steps so I can disable these INFO logs?

```
INFO connecting 127.0.0.1:3306
INFO connected to 127.0.0.1:3306
INFO close connection
```

**Comment by zookatron** [comment]
You can configure this in the connector:

```
new MySQLConnector({
  ...
  logger: { enable: false },
})
```

**Comment by LauraWebdev** [comment]
Thanks!
