### ISSUE TITLE
Module not found "https://deno.land/std/node/events.ts".

### ISSUE THREAD

**Issue by CrispenGari** [eveningkid/denodb#381]
I'm becoming in love with `denodb` a cute version of ORM with a good documentation, I started working with it today but I'm getting the error saying:

```shell
error: Module not found "https://deno.land/std/node/events.ts".
    at https://raw.githubusercontent.com/Zhomart/dex/930253915093e1e08d48ec0409b4aee800d8bd0c/lib-dyn/deps.ts:7:24
```

I don't know why is this associated with `denodb`. What maybe possibly the issue with this. Here are the logs when i try to start my deno app:

```shell
Warning Implicitly using latest version (0.186.0) for https://deno.land/std/node/stream.ts
Warning Implicitly using latest version (0.186.0) for https://deno.land/std/node/events.ts
Warning Implicitly using latest version (0.186.0) for https://deno.land/std/node/assert.ts
Warning Implicitly using latest version (0.186.0) for https://deno.land/std/node/util.ts
Warning Implicitly using latest version (0.186.0) for https://deno.land/std/node/url.ts
error: Module not found "https://deno.land/std/node/events.ts".
    at https://raw.githubusercontent.com/Zhomart/dex/930253915093e1e08d48ec0409b4aee800d8bd0c/lib-dyn/deps.ts:7:24
```
But when i remove `denodb` code it works. What maybe possibly the problem?

**Comment by CrispenGari** [comment]
I also believe that the error is raise because of the `deps.ts`  file that is in the `test` folder which is using the `std@0.115.1` which is not the latest version.

If it can be changed to:
```ts
export { assertEquals } from "https://deno.land/std@0.186.0/testing/asserts.ts";
```

to:

```ts
export { assertEquals } from "https://deno.land/std@0.115.1/testing/asserts.ts";
```

It can work, as `std/node` was removed starting from `version: 0.178.0` as mentioned [deno_std - 0.178.0](https://github.com/denoland/deno_std/releases/tag/0.178.0)

**Comment by matthewmorek** [comment]
I have exactly the same issue, though since I'm trying to use DenoDB with Deno Fresh, I have no control over dependencies (that I know of; there's no `deps.ts` file), so I can't move forward with the build.

**Comment by cesarmarinhorj** [comment]
same issue. cant use denodb...

**Comment by gaojishu** [comment]
最近尝试使用fresh，import denodb时出错，查看std版本发现178 移除了node

**Comment by jerichosiahaya** [comment]
I'm able to fix this using this solution: https://github.com/eveningkid/denodb/issues/379#issuecomment-1455195134

**Comment by jerichosiahaya** [comment]
Duplicate of #379

**Comment by CrispenGari** [comment]
I solved this issue by opening the `deno.json`  and modify it to look as follows:

```json
{
  "tasks": {
    "start": "deno run --watch --allow-sys --allow-net --allow-read --allow-env  src/index.ts"
  },
  "scopes": {
    "https://raw.githubusercontent.com/Zhomart/dex/": {
      "https://deno.land/std/": "https://deno.land/std@0.177.0/"
    }
  },
  "compilerOptions": {
    "allowJs": true,
    "lib": ["deno.window"],
    "strict": true
  }
}
```

I just added the `"scopes"` property which is this guy right here 👇 :

```json
  "scopes": {
    "https://raw.githubusercontent.com/Zhomart/dex/": {
      "https://deno.land/std/": "https://deno.land/std@0.177.0/"
    }
  }
```
