### ISSUE TITLE
How to create an unique key on Model fields

### ISSUE THREAD

**Issue by bramaudi** [eveningkid/denodb#4]
I want to create a database column and design it using `DenoDB` Model, in the doc example we can use `primaryKey: true` to mark a field (i.e. `id`) as a primary key, and my question is how to make a duplicate key?

**Comment by eveningkid** [comment]
Hello Brama,

Thanks a lot for raising this question.

You are right, I just did not add this feature. I will add an optional `unique: true` attribute shortly  (just like `primaryKey`).

I will update this issue as soon as I add the new commit.

**Comment by eveningkid** [comment]
The following should now be functional: https://github.com/eveningkid/denodb/pull/6#issue-422415202

Remember to [reload the library](https://deno.land/manual/linking_to_external_code/reloading_modules) when using it.
