### ISSUE TITLE
not able to connect mongodb

### ISSUE THREAD

**Issue by gurubaksh** [eveningkid/denodb#45]
const db = new Database('mongo', {
  uri: "mongodb+srv://username:password@cluster0-ms8o9.azure.mongodb.net/test?retryWrites=true&w=majority",
  database: 'test',
});

And url encoded connection--

const db = new Database('mongo', {
  uri: "mongodb%2Bsrv%3A%2F%2Fusername%3Apassword%40cluster0-ms8o9.azure.mongodb.net%2Ftest%3FretryWrites%3Dtrue%26w%3Dmajority",
  database: 'test',
});

both way i am getting below error 

 deno run --allow-net --allow-write --allow-read --allow-plugin --unstable main.ts

Compile file:///F:/deno/main.ts
error: The system cannot find the path specified. (os error 3)

**Comment by eveningkid** [comment]
Hey,

It is working fine for me, using a local mongo database:

```javascript
uri: "mongodb://127.0.0.1:27017",
```

Two ideas:
1) Could be related to #33, and therefore you could try to downgrade to deno 1.0.0
2) There is a password and it is not provided through the URI. I should add another way of connecting to a mongo instance using a regular option object

If you could tell me if 1) does it for you. If not, I will implement 2).

Keep in touch

**Comment by gurubaksh** [comment]
Can you please implement 2 for me.  Please also try to connect monogoDB on cloud as you are connecting on localhost. I have already started my project so for now my project is paused due to this issue.

**Comment by eveningkid** [comment]
Hello again,

This is open-source. This is a fairly new project, with mongo support just added yesterday.
I spend my free-time on this project and I do so because I love it.
If you know javascript, nothing prevents you from making a PR with the required changes.

I will add this feature, you just need to be patient.

Remember this repo is community-based, no one is paid to work on this.

**Comment by eveningkid** [comment]
It's been added. You should now be able to access more options to connect to your instance.

Remember to reload denodb by using `deno run --reload ...`.

If it does not work, it can only be either related to [deno_mongo](https://github.com/manyuanrong/deno_mongo) or to your configuration itself.

There is nothing else that can be done from denodb side.
Either way, I hope this will fix your issue.

**Comment by gurubaksh** [comment]
> Hello again,
> 
> This is open-source. This is a fairly new project, with mongo support just added yesterday.
> I spend my free-time on this project and I do so because I love it.
> If you know javascript, nothing stops you from making a PR with the required changes.
> 
> I will add this feature, you just need to be patient.
> 
> Remember this repo is community-based, no one is paid to work on this.

Thanks,  I had never worked on this kind of open source. But now you inspired me so now i will try to contribute in open source library of deno
