### ISSUE TITLE
Adding release versions

### ISSUE THREAD

**Issue by denjucks** [eveningkid/denodb#47]
Can you add release versions for various releases of denodb? It will allow users to link to various releases of the library instead of always being on the master branch (such as linking to "https://deno.land/x/denodb@1.0.0/mod.ts" when wanting to use version 1.0.0)

Also, I'm glad to see MongoDB is supported now!

**Comment by eveningkid** [comment]
Hey,

Nice suggestion! It's just the kind of things I happen to forget, sorry!

Thanks for the reminder, it should be all fine now. If not, feel free to reopen this issue.

Also, yes, the library is supporting drivers as they become available to deno. I really do my best to make this a go-to for using any database. By the way, if you have any suggestion feel free to share them with me!

See you around :)

**Comment by denjucks** [comment]
No worries! Thanks for adding the releases!
