### ISSUE TITLE
udpate failed with escapeFn problem

### ISSUE THREAD

**Issue by linuxing3** [eveningkid/denodb#48]
When run test

```typescript
import { Database, DataTypes, Model } from 'https://deno.land/x/denodb/mod.ts';
import { hash } from "https://deno.land/x/bcrypt/mod.ts";
import { assertEquals } from "../testdeps.ts";
import { mysqlOptions} from "../config/db.ts";

class User extends Model {
  static table = 'user';
  static timestamps = true;

  static fields = {
    id: {
      primaryKey: true,
      autoIncrement: true,
    },
    name: DataTypes.STRING,
    password: DataTypes.STRING,
    email: DataTypes.STRING,
  };
}
const db = new Database('mysql', mysqlOptions);
db.link([User ]);
await db.sync({ drop: false });

Deno.test("model: create", async () => {
  const password = await hash('20090909');
  const data = await User.create({
    name: 'test',
    password,
    email: 'test@qq.com'
  })
  assertEquals(data.affectedRows, 1)
});

Deno.test("model: update", async () => {
  const record = await User.where('id', 1).update({name: 'deno'})
  assertEquals(record.name, 'deno')
});

db.close()
```

Record was created, but when update, got error like this

```text
model: update
ReferenceError: Buffer is not defined
    at escapeFn (https://deno.land/x/dex/lib/query/string.js:44:16)
    at Client_MySQL.finalEscape [as _escapeBinding] (https://deno.land/x/dex/lib/query/string.js:18:12)
    at https://deno.land/x/dex/lib/client.js:151:19
    at String.replace (<anonymous>)
    at Client_MySQL._formatQuery (https://deno.land/x/dex/lib/client.js:143:16)
    at https://deno.land/x/dex/lib/interface.js:13:28
    at Array.map (<anonymous>)
    at Builder.Target.toQuery (https://deno.land/x/dex/lib/interface.js:12:8)
    at Builder.toString (https://deno.land/x/dex/lib/query/builder.js:68:17)
    at SQLTranslator.translateToQuery (https://deno.land/x/denodb/lib/translators/sql-translator.ts:209:25)
```

**Comment by loic-roux-404** [comment]
I have the same problem using different deno versions (1.0.2 / 1.0.5)

Any idea ?

**Comment by ChaimF90** [comment]
I am having the same issue with this line

`await Person.where("name", "john").update("name", "Jane");`

**Comment by eveningkid** [comment]
Hey guys,

I have been caught up with other projects and did not come back to this issue earlier :)

This might be a silly question but just to make sure: is your MySQL version 5.5 or lower?

There are some limitations at the moment with the MySQL deno driver.
I personally even switched to PostgreSQL (which isn't always ideal I understand hehe).

So yes, just keep in touch. Just want to make sure you're all using a correct MySQL version.

**Comment by eveningkid** [comment]
Alright, so I felt very curious and tried things myself using a MySQL 5.7.23 instance (go figure why it works!).

I only encountered a little naming bug with `updatedAt` which was fixed just now.

Here is the code I have:

```typescript
import { DataTypes, Database, Model } from "../mod.ts";

const db = new Database({ dialect: "mysql", debug: true }, {
  host: "localhost",
  username: "root",
  password: "",
  database: "mysql",
});

class User extends Model {
  static table = "users";
  static timestamps = true;

  static fields = {
    id: {
      primaryKey: true,
      autoIncrement: true,
    },
    name: DataTypes.STRING,
    password: DataTypes.STRING,
    email: DataTypes.STRING,
  };
}

db.link([User]);

await db.sync({ drop: true });

await User.create({
  name: "test",
  password: "20090909",
  email: "test@qq.com",
});

console.log(await User.all());
console.log(await User.where("id", 1).update({ name: "deno" }));
console.log(await User.all());
```

The only way my code differs from yours (apparently) is:
- I named the table `userS` with an s
- I am running in debug mode which shows me the queries descriptions objects

So clearly, this shouldn't affect the results. I believe this could be a matter of a version which is not supported.

This time I will wait on you guys to let me know about your MySQL version so we can figure this out.

Keep in touch

**Comment by loic-roux-404** [comment]
mysql 8.0.14...

**Comment by ChaimF90** [comment]
I actually ran into this issue using sqlite as well. Gonna go back and try this again using mysql to see if it works.

**Comment by eveningkid** [comment]
@ChaimF90 that's odd. If you could share the full example, that would help for debugging.

**Comment by ChaimF90** [comment]
Here is my code

```
import { Database, Model, DataTypes } from "https://deno.land/x/denodb/mod.ts";

const db = new Database("sqlite3", {
  filepath: "./db.sqlite",
});

class Person extends Model {
  static table = "people";

  static fields = {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
    },
    name: DataTypes.STRING,
  };
}

db.link([Person]);
await db.sync();

await Person.create({name: "John"});
await Person.where("id", 1).update({name: "Jane"});

const all = await Person.all();
console.log(all);
```

And this is the error I get

> Uncaught ReferenceError: Buffer is not defined

**Comment by eveningkid** [comment]
@ChaimF90 Odd, it runs fine on my end.

Try to run using `deno run --reload ...` to make sure you have the latest version.

**Comment by ChaimF90** [comment]
that worked! Thanks! Love this library btw

**Comment by eveningkid** [comment]
Grand, I am glad you like it Chaim :)

Well, as it seems the issue has been solved, I will close the issue for now.

@linuxing3 do not hesitate to reopen it if your issue is still not fixed.

Other than that, have a great day guys

**Comment by linuxing3** [comment]
Thanks
