### ISSUE TITLE
Offset option not found

### ISSUE THREAD

**Issue by ariframadhani** [eveningkid/denodb#49]
I am trying to make a pagination, but looks like there's no option for offsetting the entries?

**Comment by eveningkid** [comment]
Hey Arin,

Thanks for the suggestion, you are totally right about this :)

I will add something like this straight away:
```javascript
await Flight.offset(10).limit(10).get();
```

If you have any other suggestion on pagination more specifically, let me know on this issue!

Keep in touch

**Comment by eveningkid** [comment]
It's been added, you'll just need to run `deno run --reload ...` to get the update :)

I will keep this issue opened for another day, in case you have any feedback. Will close it otherwise

**Comment by ariframadhani** [comment]
Wow thanks that was fast :D this is exactly what I want. Thanks again @eveningkid

**Comment by eveningkid** [comment]
Great, I’m open to feedback if you have any other suggestion!

Enjoy the weekend :)
