### ISSUE TITLE
error: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by lucarducci** [eveningkid/denodb#52]
Error:

`error: No such file or directory (os error 2)`

on the connection:

```
  const db = new Database("mongo", {
    uri: "mongodb://localhost:27017",
    database: "test",
  });
```

**Comment by eveningkid** [comment]
Hey Luca,

Before asking a question, please check previous issues as [one has the exact same title than yours](https://github.com/eveningkid/denodb/issues/33).

This was fixed with deno 1.0.5.

Best
