### ISSUE TITLE
Return value of Model class .delete and .update methods

### ISSUE THREAD

**Issue by SquareMesh** [eveningkid/denodb#55]
Not sure if I'm using in intended way ...

Have defined class LookupCodes extending class Model.
Have REST Api function to perform delete for existing LookupCode by id 
NOTE : Focus on delete() for example, but applies to update() also.

**Method #1**
First step check if record exists by id for validation / messaging purposes 

`const lookupCode = await LookupCodes.select().find(paramId);`

Interestingly LookupCode is not instantiated (unless denodb did this) but returns workable object if match found.
If find fails to locate record then lookupCode is undefined and can be used for error reporting

The returned object "lookupCode" can be used to perform update.

`const result = await lookupCode.update();`

This works, but I'm not sure I can interogate "result" to determine if update was truly successfull.  It returns an object value.

So ..

class.find() useful for returning object and then use for further action
class.delete() useful as action is performed, but outcome unclear

**Method #2**
When I compare this approach with using where() + delete()

LookupCodes.where("id", id).delete()

I get a result (and not object) which indicates rowsAffected which can be used for error checking / messaging.

I probably suspect that Method #2 is the expected approach.  But the class approach was handy when returning an object that could then be used.

Can class use of delete() or update() provide feedback in alternate way to indicate rowsAffected?

Hope this makes sense and apologies if use of terms not quite correct.  Let me know if you need more info and whether I'm using a flawed approach that happened to do some good things.

**Comment by eveningkid** [comment]
Hey,

Thanks for raising this question, it's interesting.

So let me quickly explain my first way of thinking. Initially, I expected this:
```javascript
const code = await LookupCodes.find(1);
const updatedCode = await code.update({ code: 'xxx' });
```
But, from what I understand, you would need the following:
```javascript
const resultsFromUpdate = await code.update({ code: 'xxx' });
// resultsFromUpdate would then have "rowAffected" etc.
```
I think your approach is better and more in sync with classes behaviour i.e. `Model.update`, `Model.delete` which won't return the model itself but the results from the query.

Just to make sure, you wish to use things the way I wrote it with `resultsFromUpdate` right?

**Comment by SquareMesh** [comment]
Correct.  LookupCodes.find() has return a class object (representing our model) but when calling the Update() method of our model object we could instead get object representing outcome i.e. rowsAffected.

Code wise I would approach use as follows :

const code = await LookupCodes.find(1);
const {rowsAffected} = await code.update({ code: 'xxx' });
if (rowsAffected===1) { ....}

The above reflect one change.  Related to this is minor issue (and this might be a non-issue and considered working as intended) relating to the return value when directly using class methods for update(), delete()

LookupCodes.where("id", 1).update({code_id: "X"})
LookupCodes.where("id", 1).delete();

These do return rowsAffected but they do so as a class object
LookupCodes { affectedRows: 1, lastInsertId: 0 }

Ideally it would be good if results were return as object { affectedRows: 1, lastInsertId: 0 }
allowing use case

const {rowsAffected} = await LookupCodes.where("id", 1).update({code_id: "X"})

Prior to finding "denodb" I was using "mysql" directly and using its return values in this way.

At the moment when class methods directly I require the following ..

const updateResult = await LookupCodeModel.editLookupCode(id,data);
const affectedRows = updateResult["affectedRows"]
if (rowsAffected===1) { ....}

Part of this was my own learning when understanding the return value. It's workable but little more involved.  I guess also that return value of class object LookupCode when using this methods directly is misaligned as they don't represent structure of the model.

Hope this makes sense.  Happy to clarify further if needed.

**Comment by eveningkid** [comment]
Thanks for confirming, I hope this little change will make things easier for you!

It should now be working with #59. Just remember to reload, `deno run --reload ...` and you should be good to go.

If not, just reopen the issue okay?

See you around :)

**Comment by SquareMesh** [comment]
Hi @eveningkid ,

Thanks again for this change.  The fix provides a better result.  One follow up question is whether it should return Model Class object type or just plain object type.  This is minor really.

Currently value is returned as `LookupCodes { affectedRows: 1, lastInsertId: 0 }`

Which makes it seem likes it a class object of LookupCodes but it's not really.  Do you think it's possible or worthwhile to return as base object so data elements can be referenced directly.

const {rowsAffected} = await resultFind.delete();

PS.  I can't re-open, not that I wanted to before asking question.  Let me know if you want a new issue if you want to track change - if worthwhile doing.
