### ISSUE TITLE
autoincrement

### ISSUE THREAD

**Issue by nestorPons** [eveningkid/denodb#64]
Hola, no se si estoy en lo cierto pero , se supone que al poner autoincremento un campo id deberia de generarse un contador en dicho campo sin tener que escribirlo manualente pero en la base de datos mondodb eso no es asi simplemente pone una cadena tipo _id de mongo pero no un campo incremental. 

Must it have that behavior or is it a bug?

 static table = "test";
      
        static fields = {     
            _id_autoincrement: {
                primaryKey: true,
                type: DATA_TYPES.INTEGER, 
                autoIncrement: true
            }, 
            field1: {
                type: DATA_TYPES.STRING,
                length: 2,   //  <-- does not throw an exception
            }
        };

Saludos

**Comment by eveningkid** [comment]
Hola Nestor,

Tienes razón, esta opción no está disponible con MongoDB. ¡Debería actualizar la documentación!

You should manually set an ID when using MongoDB (you could generate a unique id using [this library](https://github.com/jeanlescure/short_uuid)), without the `autoIncrement` option in your model.

Sorry, this was my best spanish haha!

Hope this will still do it for you, thanks for raising your concern :)

Have a nice day
