### ISSUE TITLE
is MS SQL support planned in the future?

### ISSUE THREAD

**Issue by opensas** [eveningkid/denodb#67]
Just that, are you going to support MS SQL in the near future?

**Comment by eveningkid** [comment]
Hello,

Well this will happen if we see a MS SQL driver for Deno which doesn't exist (yet).

I am sure this could be useful for the community, so if you work on such project, I would be more than happy to integrate it into denodb.

I hope this can motivate you to work on such project if you want to see it happen :)

Have a nice day
