### ISSUE TITLE
Typing autocomplete for Model Records

### ISSUE THREAD

**Issue by swiftsword94** [eveningkid/denodb#68]
Can we get typing/autocomplete for being able to update values on the model directly? The fields don't show up when running intellisense on an instance of the model.

```
import { DataTypes, Database, Model } from 'https://deno.land/x/denodb/mod.ts';

const db = new Database('postgres', {
  host: '...',
  username: 'user',
  password: 'password',
  database: 'airlines',
});

class Flight extends Model {
  static table = 'flights';
  static timestamps = true;

  static fields = {
    id: { primaryKey: true, autoIncrement: true },
    departure: DataTypes.STRING,
    destination: DataTypes.STRING,
    flightDuration: DataTypes.FLOAT,
  };

  static defaults = {
    flightDuration: 2.5,
  };
}

const flight = new Flight();

///////////////
// the following does not show intellisense   vvvvvvvvvv
////////////////
flight.departure = 'Dublin';
flight.destination = 'Paris';
```

**Comment by eveningkid** [comment]
Hello,

Good question, I actually already tried to work on this. The only way to get intellisense as of right now is to add the following in your case:

```javascript
class Flight extends Model {
  // ...after static methods
  departure!: string;
  destination!: string;
  // ...and so on
}
```

I am not a huge fan of this syntax. I thought of switching to decorators which would solve the issue but this might push people away from the simplicity of denodb.

I might make this up to the dev, to choose between decorators or `static fields`.

So anyways, here you have it :)

Thanks for asking and do not hesitate if anything else comes to your mind!
