### ISSUE TITLE
Are there model events?

### ISSUE THREAD

**Issue by iarkaroy** [eveningkid/denodb#69]
I am not sure whether this is already documented but I could not find it in the doc. I would like to know if there are model events to listen for like `creating`, `created`, `updating`, `updated` etc. It will be really helpful to do tasks on such events like cleaning up when deleting etc. Also it will be nice place to set uuid, if needed (I don't know if uuid is supported out-of-the-box). Pointing it out based on my experience with eloquent.

Thanks.

**Comment by eveningkid** [comment]
Hello Arka,

Thanks a lot for this suggestion, it is actually a very nice idea :)

It is not available right now but I would like to implement it. Here are my first thoughts:

```javascript
Flight.on('created', (model) => {

});

class Flight extends Model {
  onCreated(model) {

  }
}
```

Regarding the events, which ones do we need? Straight off from your message I would only think of the following:
- creating/created
- updating/updated
- deleting/deleted

Are we missing any other?

Let me know about your thoughts. Nothing is settled so let's share ideas first!

Keep in touch :)

**Comment by iarkaroy** [comment]
Thanks for the prompt response. Your initial thoughts look sufficient to me. The events that you have listed should serve the purpose well. Thanks for such a nice library. Keep it up.

**Comment by eveningkid** [comment]
Great, I will work on this later this week. I will also update this issue whenever it's ready.

Thanks for the kind words, it's well appreciated :)

Have a great week
