### ISSUE TITLE
sync tries to always create a table

### ISSUE THREAD

**Issue by AntouanK** [eveningkid/denodb#7]
Hi there.

following the examples to work on a small side-project I have.

if I use 
```js
export class SessionModel extends Model {
  static table = "sessions";
  static timestamps = true;
  static fields = {
    id: {
      primaryKey: true,
      autoIncrement: true,
    },
    startTimestamp: DATA_TYPES.INTEGER,
    endTimestamp: DATA_TYPES.INTEGER,
    createdAt: DATA_TYPES.INTEGER,
    price: DATA_TYPES.STRING,
    category: DATA_TYPES.STRING,
    subCategory: DATA_TYPES.STRING,
    state: DATA_TYPES.STRING,
    withUser: DATA_TYPES.STRING,
    notes: DATA_TYPES.STRING,
  };
}

db.link([SessionModel]);

await db.sync({ drop: false /* true */ });
``` 
, the first time it runs, it creates the tables and everything is fine.
Every time after that, it fails trying to create a table

( logs from my 2 containers, one with the postgres db, and one with the deno api )
```
bp-db_1   | 2020-05-24 19:40:10.668 UTC [306] ERROR:  relation "sessions" already exists
bp-db_1   | 2020-05-24 19:40:10.668 UTC [306] STATEMENT:  create table "sessions" ("id" serial primary key, "startTimestamp" integer, "endTimestamp" integer, "createdAt" integer, "price" varchar(255), "category" varchar(255), "subCategory" varchar(255), "state" varchar(255), "withUser" varchar(255), "notes" varchar(255), "created_at" timestamptz not null default CURRENT_TIMESTAMP, "updated_at" timestamptz not null default CURRENT_TIMESTAMP)
bp-api_1  | error: Uncaught PostgresError: relation "sessions" already exists
bp-api_1  |   return new PostgresError(errorFields);
bp-api_1  |          ^
bp-api_1  |     at parseError (https://deno.land/x/postgres/error.ts:105:10)
bp-api_1  |     at Connection._processError (https://deno.land/x/postgres/connection.ts:430:19)
bp-api_1  |     at Connection._simpleQuery (https://deno.land/x/postgres/connection.ts:297:20)
bp-api_1  |     at async Connection.query (https://deno.land/x/postgres/connection.ts:539:16)
bp-api_1  |     at async Client.query (https://deno.land/x/postgres/client.ts:24:12)
bp-api_1  |     at async PostgresConnector.query (https://deno.land/x/denodb/lib/connectors/postgres-connector.ts:45:21)
bp-api_1  |     at async Function._createInDatabase (https://deno.land/x/denodb/lib/model.ts:75:5)
bp-api_1  |     at async Promise.all (index 0)
bp-api_1  |     at async file:///app/db.ts:32:1
```

If I switch `drop` to `true`, it will wipe out everything (after the first time)

I'm sure I'm missing something. How can I make it create the table only when it doesn't exist??

Thank you.

**Comment by eveningkid** [comment]
Hey Antonis,

You are right, it actually tries to create the tables every single time.
I will work on this right now and update this issue.

**Comment by eveningkid** [comment]
It should now be functional.
Just remember to use `--reload` to make sure you get the last library version.

Feel free to get in touch if you're still facing an issue! Or anything else obviously :)

**Comment by AntouanK** [comment]
Hey @eveningkid 
Thanks for getting a fix to this.
I don't get any errors anymore, but I think it wipes out the table every time I start it :/ 
Cannot persist any data in the table...

**Comment by eveningkid** [comment]
Even with `drop` set to `false`?
await db.sync({ drop: false /* true */ });

**Comment by AntouanK** [comment]
yeah, my bad, I forgot the "drop: true".
I removed that and it's fine.

thanks :+1:

**Comment by chovy** [comment]
I'm still getting this error. If I use drop: true then data is wiped.

if i remove it, then it gripes that table already exists.

**Comment by slim-hmidi** [comment]
I have the same issue here, with `drop` it removes the table and recreates it. Without it, it throws an issue that the table already exists.
There is no solution to persist the data of the created tables and not erase them for every server restart?
