### ISSUE TITLE
Contraint 

### ISSUE THREAD

**Issue by winn92** [eveningkid/denodb#71]
How to implement cascade deletion?

**Comment by eveningkid** [comment]
Hey,

Great question. It is actually the default behaviour if you [look closely at the code](https://github.com/eveningkid/denodb/blob/master/lib/helpers/fields.ts#L25:L30).

Have you ran into an issue where it wouldn't delete them on cascade?

Let me know so we can figure this out together.

Keep in touch

**Comment by eveningkid** [comment]
If you ever have this issue again, please let me know so we can reopen it.
So far I think the default behaviour follows `on delete cascade`.

Have a great week!
