### ISSUE TITLE
Error for postgres: string | URL

### ISSUE THREAD

**Issue by Focinfi** [eveningkid/denodb#83]
error: TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/x/dex/lib/deps/path/win32.ts:911:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/x/dex/lib/deps/path/posix.ts:433:18

**Comment by eveningkid** [comment]
Hey Frank,

This is a duplicate from #78.

We are still waiting on a solution as this relies on a library that did not upgrade yet...

We need to be patient on this one
