### ISSUE TITLE
PostgresError: foreign key constraint ... cannot be implemented

### ISSUE THREAD

**Issue by lizraeli** [eveningkid/denodb#85]
Thanks again for the awesome work on this project.
I can see that this error was reported at the end of another thread (#76) but felt it would be easier to start a new one and add more details. This error happens when using Postgres as the database, and trying to create a model with a "belongs to" relationship. I have realized what the source of the issue is in the library, but first I'll add a small code example that raises it:

```ts

  const db = new Database("postgres", {
    host: "127.0.0.1",
    username: "admin",
    password: "",
    database: "conduit",
    port: 5432,
  });
  
  class User extends Model {
    static table = "users";
    static timestamps = true;
  
    static fields = {
      id: { primaryKey: true, type: DataTypes.INTEGER, autoIncrement: true },
    };
  }
  
  class Article extends Model {
    static table = "articles";
    static timestamps = true;
  
    static fields = {
      id: { primaryKey: true, autoIncrement: true },
      title: { type: DataTypes.STRING, required: true },
      userId: Relationships.belongsTo(User)
    }; 
  }

  db.link([ User, Article]);
  await db.sync({ drop: true });
```

On trying to execute the above code, the following error is raised:

```
error:  PostgresError: foreign key constraint "articles_user_id_foreign" cannot be implemented
    at parseError (https://deno.land/x/postgres/error.ts:106:10)
    at Connection._processError (https://deno.land/x/postgres/connection.ts:434:19)
    at Connection._simpleQuery (https://deno.land/x/postgres/connection.ts:340:22)
    at async Connection.query (https://deno.land/x/postgres/connection.ts:546:16)
    at async Client.query (https://deno.land/x/postgres/client.ts:25:12)
    at async PostgresConnector.query (https://deno.land/x/denodb/lib/connectors/postgres-connector.ts:49:9)
    at async Database.query (https://deno.land/x/denodb/lib/database.ts:156:18)
    at async Function.createTable (https://deno.land/x/denodb/lib/model.ts:122:5)
    at async Database.sync (https://deno.land/x/denodb/lib/database.ts:124:7)
    at async file:///Users/lev.izraelit/realworld/deno/db.ts:8:4
```

I have a Postgres server running in a terminal, and could see the following being logged:
```
 [42006] ERROR:  foreign key constraint "articles_user_id_foreign" cannot be implemented
 [42006] DETAIL:  Key columns "user_id" and "id" are of incompatible types: character varying and integer.
```

Upon some investigation into the codebase, I was able to pinpoint the issue to the following code in [lib/helpers/fields.ts](https://github.com/eveningkid/denodb/blob/6564531918ceeba17e45c9c32e3b4923d4d6d390/lib/helpers/fields.ts#L25)
```ts
  if (typeof fieldOptions.type === "object") {
    if (fieldOptions.type.relationship) {
      const relationshipPKName = fieldOptions.type.relationship.model
        .getComputedPrimaryKey();

      table.string(fieldOptions.name);
```
That is, if the field type is `relationship`, we try to create an sql field with a string type, and not an integer type, which is the type that's returned by the [Relationships.belongsTo](https://github.com/eveningkid/denodb/blob/f22446241ccc24b61d7338ba3667f72912415d51/lib/relationships.ts#L17) function. I can confirm that changing the above code locally to
```ts
table.integer(fieldOptions.name);
```
solved the problem for me. I thought to make a PR, but I see that it was originally `table.integer` in the code, before being updated to `table.string` in a commit titled [Fix MySQL connector queries processing](https://github.com/eveningkid/denodb/commit/6564531918ceeba17e45c9c32e3b4923d4d6d390#diff-87c8cef5bffe855c9ce077afe91b78ffR25). Possibly that change was needed to resolve some issue with MySQL?

**Comment by eveningkid** [comment]
Hey Lev,

Thanks for raising this issue, it's always good having more details on this :)
You took time to dive in the code an repo history, that's really cool.

About your question, there is actually already a PR for this #80 which is on hold at the moment.

Not too sure when I will have enough time to get back at least part-time on this project.
Hope this can be solved shortly by the PR's author.

Keep in touch!

**Comment by eveningkid** [comment]
#80 fixed this issue. Just cleaning things a little bit :)

Have a great day!

**Comment by lizraeli** [comment]
Thanks @eveningkid !
