### ISSUE TITLE
Question - In Typescript file I get an error "Property 'departure' does not exist on type 'Flight'."

### ISSUE THREAD

**Issue by thecodeholic** [eveningkid/denodb#86]
In Javascript file the code works fine, but in Typescript I get the following error.
Do you have any idea?

![image](https://user-images.githubusercontent.com/4627922/89007042-01704700-d319-11ea-8c9b-5ffd39aa577b.png)

**Comment by eveningkid** [comment]
Hey,

Thanks for getting in touch.

I will need some code to help you with that. Could you show me where your `Flight` model is declared?

This should be simple to fix.

Keep in touch

**Comment by thecodeholic** [comment]
The code is the exact same as written in README.
I just copied and pasted the code into editor.

**Comment by eveningkid** [comment]
Hello again,

Thanks for clarifying :)

Then you can solve this easily by adding the following:

```typescript
class Flight extends Model {
  static fields = {
    // ...
  };
  
  eachFieldNameWithAnExclamationMark!: string;
  departure!: string;
  // ...
}
```

This should do it, have a great day!

**Comment by eveningkid** [comment]
Hi,

Just realised my last answer should have solved your issue.

If not, feel free to reply below (but hopefully you're good!).
