### ISSUE TITLE
error encountered after importing a model

### ISSUE THREAD

**Issue by marckent04** [eveningkid/denodb#87]
after import to this model :
import { Model, DataTypes } from 'https://deno.land/x/denodb/mod.ts';

export default class User extends Model {
    static table = 'users';
    static timestamps = true;

    static fields = {
        id: {
            primaryKey: true,
            autoIncrement: true
        },
        firstName: DataTypes.STRING,
        lastName: DataTypes.STRING,
        birthday: DataTypes.DATE,
        username: DataTypes.STRING,
        password: DataTypes.STRING
    };
}

i have this error :

`[0m[38;5;10mCheck[0m file:///home/*******************
[0m[1m[31merror[0m: [0m[1mTS7006[0m [ERROR]: Parameter 'str' implicitly has an 'any' type.
function lexer(str) {
[0m[31m               ~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m9[0m:[0m[38;5;11m16[0m

[0m[1mTS7006[0m [ERROR]: Parameter 'str' implicitly has an 'any' type.
function parse(str, options) {
[0m[31m               ~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m144[0m:[0m[38;5;11m16[0m

[0m[1mTS7006[0m [ERROR]: Parameter 'options' implicitly has an 'any' type.
function parse(str, options) {
[0m[31m                    ~~~~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m144[0m:[0m[38;5;11m21[0m

[0m[1mTS7006[0m [ERROR]: Parameter 'type' implicitly has an 'any' type.
  var tryConsume = function (type) {
[0m[31m                             ~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m158[0m:[0m[38;5;11m30[0m

[0m[1mTS7006[0m [ERROR]: Parameter 'type' implicitly has an 'any' type.
  var mustConsume = function (type) {
[0m[31m                              ~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m162[0m:[0m[38;5;11m31[0m

[0m[1mTS2403[0m [ERROR]: Subsequent variable declarations must have the same type.  Variable 'prefix' must be of type 'any', but here has type 'string'.
      var prefix = consumeText();
[0m[31m          ~~~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m225[0m:[0m[38;5;11m11[0m

    'prefix' was also declared here.
          var prefix = char || "";
    [0m[38;5;14m          ~~~~~~[0m
        at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m188[0m:[0m[38;5;11m11[0m

[0m[1mTS2339[0m [ERROR]: Property 'parse' does not exist on type '{}'.
exports.parse = parse;
[0m[31m        ~~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m246[0m:[0m[38;5;11m9[0m

[0m[1mTS7006[0m [ERROR]: Parameter 'str' implicitly has an 'any' type.
function compile(str, options) {
[0m[31m                 ~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m251[0m:[0m[38;5;11m18[0m

[0m[1mTS7006[0m [ERROR]: Parameter 'options' implicitly has an 'any' type.
function compile(str, options) {
[0m[31m                      ~~~~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m251[0m:[0m[38;5;11m23[0m

[0m[1mTS2339[0m [ERROR]: Property 'compile' does not exist on type '{}'.
exports.compile = compile;
[0m[31m        ~~~~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m255[0m:[0m[38;5;11m9[0m

[0m[1mTS7006[0m [ERROR]: Parameter 'tokens' implicitly has an 'any' type.
function tokensToFunction(tokens, options) {
[0m[31m                          ~~~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m260[0m:[0m[38;5;11m27[0m

[0m[1mTS7006[0m [ERROR]: Parameter 'options' implicitly has an 'any' type.
function tokensToFunction(tokens, options) {
[0m[31m                                  ~~~~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m260[0m:[0m[38;5;11m35[0m

[0m[1mTS7006[0m [ERROR]: Parameter 'x' implicitly has an 'any' type.
      encode = _a === void 0 ? function (x) {
[0m[31m                                         ^[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m267[0m:[0m[38;5;11m42[0m

[0m[1mTS7006[0m [ERROR]: Parameter 'token' implicitly has an 'any' type.
  var matches = tokens.map(function (token) {
[0m[31m                                     ~~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m273[0m:[0m[38;5;11m38[0m

[0m[1mTS7006[0m [ERROR]: Parameter 'data' implicitly has an 'any' type.
  return function (data) {
[0m[31m                   ~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m278[0m:[0m[38;5;11m20[0m

[0m[1mTS2339[0m [ERROR]: Property 'tokensToFunction' does not exist on type '{}'.
exports.tokensToFunction = tokensToFunction;
[0m[31m        ~~~~~~~~~~~~~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m336[0m:[0m[38;5;11m9[0m

[0m[1mTS7006[0m [ERROR]: Parameter 'str' implicitly has an 'any' type.
function match(str, options) {
[0m[31m               ~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m341[0m:[0m[38;5;11m16[0m

[0m[1mTS7006[0m [ERROR]: Parameter 'options' implicitly has an 'any' type.
function match(str, options) {
[0m[31m                    ~~~~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m341[0m:[0m[38;5;11m21[0m

[0m[1mTS7034[0m [ERROR]: Variable 'keys' implicitly has type 'any[]' in some locations where its type cannot be determined.
  var keys = [];
[0m[31m      ~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m342[0m:[0m[38;5;11m7[0m

[0m[1mTS7005[0m [ERROR]: Variable 'keys' implicitly has an 'any[]' type.
  var re = pathToRegexp(str, keys, options);
[0m[31m                             ~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m343[0m:[0m[38;5;11m30[0m

[0m[1mTS7005[0m [ERROR]: Variable 'keys' implicitly has an 'any[]' type.
  return regexpToFunction(re, keys, options);
[0m[31m                              ~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m344[0m:[0m[38;5;11m31[0m

[0m[1mTS2339[0m [ERROR]: Property 'match' does not exist on type '{}'.
exports.match = match;
[0m[31m        ~~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m347[0m:[0m[38;5;11m9[0m

[0m[1mTS7006[0m [ERROR]: Parameter 're' implicitly has an 'any' type.
function regexpToFunction(re, keys, options) {
[0m[31m                          ~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m352[0m:[0m[38;5;11m27[0m

[0m[1mTS7006[0m [ERROR]: Parameter 'keys' implicitly has an 'any' type.
function regexpToFunction(re, keys, options) {
[0m[31m                              ~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m352[0m:[0m[38;5;11m31[0m

[0m[1mTS7006[0m [ERROR]: Parameter 'options' implicitly has an 'any' type.
function regexpToFunction(re, keys, options) {
[0m[31m                                    ~~~~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m352[0m:[0m[38;5;11m37[0m

[0m[1mTS7006[0m [ERROR]: Parameter 'x' implicitly has an 'any' type.
      decode = _a === void 0 ? function (x) {
[0m[31m                                         ^[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m358[0m:[0m[38;5;11m42[0m

[0m[1mTS7006[0m [ERROR]: Parameter 'pathname' implicitly has an 'any' type.
  return function (pathname) {
[0m[31m                   ~~~~~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m361[0m:[0m[38;5;11m20[0m

[0m[1mTS7006[0m [ERROR]: Parameter 'i' implicitly has an 'any' type.
    var _loop_1 = function (i) {
[0m[31m                            ^[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m368[0m:[0m[38;5;11m29[0m

[0m[1mTS7006[0m [ERROR]: Parameter 'value' implicitly has an 'any' type.
        params[key.name] = m[i].split(key.prefix + key.suffix).map(function (value) {
[0m[31m                                                                             ~~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m374[0m:[0m[38;5;11m78[0m

[0m[1mTS2339[0m [ERROR]: Property 'regexpToFunction' does not exist on type '{}'.
exports.regexpToFunction = regexpToFunction;
[0m[31m        ~~~~~~~~~~~~~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m394[0m:[0m[38;5;11m9[0m

[0m[1mTS7006[0m [ERROR]: Parameter 'str' implicitly has an 'any' type.
function escapeString(str) {
[0m[31m                      ~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m399[0m:[0m[38;5;11m23[0m

[0m[1mTS7006[0m [ERROR]: Parameter 'options' implicitly has an 'any' type.
function flags(options) {
[0m[31m               ~~~~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m407[0m:[0m[38;5;11m16[0m

[0m[1mTS7006[0m [ERROR]: Parameter 'path' implicitly has an 'any' type.
function regexpToRegexp(path, keys) {
[0m[31m                        ~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m415[0m:[0m[38;5;11m25[0m

[0m[1mTS7006[0m [ERROR]: Parameter 'keys' implicitly has an 'any' type.
function regexpToRegexp(path, keys) {
[0m[31m                              ~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m415[0m:[0m[38;5;11m31[0m

[0m[1mTS7006[0m [ERROR]: Parameter 'paths' implicitly has an 'any' type.
function arrayToRegexp(paths, keys, options) {
[0m[31m                       ~~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m439[0m:[0m[38;5;11m24[0m

[0m[1mTS7006[0m [ERROR]: Parameter 'keys' implicitly has an 'any' type.
function arrayToRegexp(paths, keys, options) {
[0m[31m                              ~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m439[0m:[0m[38;5;11m31[0m

[0m[1mTS7006[0m [ERROR]: Parameter 'options' implicitly has an 'any' type.
function arrayToRegexp(paths, keys, options) {
[0m[31m                                    ~~~~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m439[0m:[0m[38;5;11m37[0m

[0m[1mTS7006[0m [ERROR]: Parameter 'path' implicitly has an 'any' type.
  var parts = paths.map(function (path) {
[0m[31m                                  ~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m440[0m:[0m[38;5;11m35[0m

[0m[1mTS7006[0m [ERROR]: Parameter 'path' implicitly has an 'any' type.
function stringToRegexp(path, keys, options) {
[0m[31m                        ~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m450[0m:[0m[38;5;11m25[0m

[0m[1mTS7006[0m [ERROR]: Parameter 'keys' implicitly has an 'any' type.
function stringToRegexp(path, keys, options) {
[0m[31m                              ~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m450[0m:[0m[38;5;11m31[0m

[0m[1mTS7006[0m [ERROR]: Parameter 'options' implicitly has an 'any' type.
function stringToRegexp(path, keys, options) {
[0m[31m                                    ~~~~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m450[0m:[0m[38;5;11m37[0m

[0m[1mTS7006[0m [ERROR]: Parameter 'tokens' implicitly has an 'any' type.
function tokensToRegexp(tokens, keys, options) {
[0m[31m                        ~~~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m458[0m:[0m[38;5;11m25[0m

[0m[1mTS7006[0m [ERROR]: Parameter 'keys' implicitly has an 'any' type.
function tokensToRegexp(tokens, keys, options) {
[0m[31m                                ~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m458[0m:[0m[38;5;11m33[0m

[0m[1mTS7006[0m [ERROR]: Parameter 'options' implicitly has an 'any' type.
function tokensToRegexp(tokens, keys, options) {
[0m[31m                                      ~~~~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m458[0m:[0m[38;5;11m39[0m

[0m[1mTS7006[0m [ERROR]: Parameter 'x' implicitly has an 'any' type.
      encode = _d === void 0 ? function (x) {
[0m[31m                                         ^[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m470[0m:[0m[38;5;11m42[0m

[0m[1mTS2339[0m [ERROR]: Property 'tokensToRegexp' does not exist on type '{}'.
exports.tokensToRegexp = tokensToRegexp;
[0m[31m        ~~~~~~~~~~~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m525[0m:[0m[38;5;11m9[0m

[0m[1mTS7006[0m [ERROR]: Parameter 'path' implicitly has an 'any' type.
function pathToRegexp(path, keys, options) {
[0m[31m                      ~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m534[0m:[0m[38;5;11m23[0m

[0m[1mTS7006[0m [ERROR]: Parameter 'keys' implicitly has an 'any' type.
function pathToRegexp(path, keys, options) {
[0m[31m                            ~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m534[0m:[0m[38;5;11m29[0m

[0m[1mTS7006[0m [ERROR]: Parameter 'options' implicitly has an 'any' type.
function pathToRegexp(path, keys, options) {
[0m[31m                                  ~~~~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m534[0m:[0m[38;5;11m35[0m

[0m[1mTS2339[0m [ERROR]: Property 'pathToRegexp' does not exist on type '{}'.
exports.pathToRegexp = pathToRegexp;
[0m[31m        ~~~~~~~~~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m540[0m:[0m[38;5;11m9[0m

[0m[1mTS2339[0m [ERROR]: Property '__esModule' does not exist on type '{}'.
const __esModule = exports.__esModule;
[0m[31m                           ~~~~~~~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m541[0m:[0m[38;5;11m28[0m

[0m[1mTS2339[0m [ERROR]: Property 'parse' does not exist on type '{}'.
const _parse = exports.parse,
[0m[31m                       ~~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m542[0m:[0m[38;5;11m24[0m

[0m[1mTS2339[0m [ERROR]: Property 'compile' does not exist on type '{}'.
      _compile = exports.compile,
[0m[31m                         ~~~~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m543[0m:[0m[38;5;11m26[0m

[0m[1mTS2339[0m [ERROR]: Property 'tokensToFunction' does not exist on type '{}'.
      _tokensToFunction = exports.tokensToFunction,
[0m[31m                                  ~~~~~~~~~~~~~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m544[0m:[0m[38;5;11m35[0m

[0m[1mTS2339[0m [ERROR]: Property 'match' does not exist on type '{}'.
      _match = exports.match,
[0m[31m                       ~~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m545[0m:[0m[38;5;11m24[0m

[0m[1mTS2339[0m [ERROR]: Property 'regexpToFunction' does not exist on type '{}'.
      _regexpToFunction = exports.regexpToFunction,
[0m[31m                                  ~~~~~~~~~~~~~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m546[0m:[0m[38;5;11m35[0m

[0m[1mTS2339[0m [ERROR]: Property 'tokensToRegexp' does not exist on type '{}'.
      _tokensToRegexp = exports.tokensToRegexp,
[0m[31m                                ~~~~~~~~~~~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m547[0m:[0m[38;5;11m33[0m

[0m[1mTS2339[0m [ERROR]: Property 'pathToRegexp' does not exist on type '{}'.
      _pathToRegexp = exports.pathToRegexp;
[0m[31m                              ~~~~~~~~~~~~[0m
    at [0m[38;5;14mhttps://jspm.dev/npm:path-to-regexp@6.1.0!cjs[0m:[0m[38;5;11m548[0m:[0m[38;5;11m31[0m

Found 58 errors.
`

thanks for help

**Comment by eveningkid** [comment]
Salut Marc-Henry,

I would like to help. Please share a better formatted error so that we can provide some help.

Let me know once it's done so I can give this another look.

Keep in touch

**Comment by eveningkid** [comment]
Hello again,

I just released 1.0.6 that might have been the issue.

If I don't have code to reproduce your issue I will have to close it.

Let me know

**Comment by eveningkid** [comment]
Hi Marc,

It's been months so I believe that other version indeed fixed your issue, I'll close this!
