### ISSUE TITLE
Model import problem

### ISSUE THREAD

**Issue by DavidCMeier** [eveningkid/denodb#89]
When I tried to use Model i recived this error: 

``
error: Import 'https://deno.land/x/color/index.ts' failed: 404 Not Found
``

Just using this: 
```export { Database, Model } from `'https://deno.land/x/denodb/mod.ts';```

here is a demo: 
https://repl.it/@DavidCMeier/DenoDb-problem-model

**Comment by michaelachrisco** [comment]
I can report the same issue.

**Comment by michaelachrisco** [comment]
It looks like it may have been removed or moved:
When you go to: https://deno.land/x/color/index.ts
```
No uploaded versions
This module name has been reserved for a repository, but no versions have been uploaded yet. Modules that do not upload a version within 30 days of registration will be removed. If you are the owner of this module, please re-add the GitHub repository with deno.land/x (by following the instructions at https://deno.land/x#add), and publish a new version.
```

**Comment by michaelachrisco** [comment]
It appears as though the only place this package is used is within https://github.com/eveningkid/denodb/blob/8eca58d4f2eeec9755c03e49de8e84083be13301/lib/helpers/log.ts

**Comment by eveningkid** [comment]
Hey David,

Thanks for reporting this issue.

#90 should fix it. Do not hesitate to reopen the issue if it didn't.

Enjoy the weekend!

**Comment by fredlemieux** [comment]
Thanks for this fix! Quick question, these changes don't show up on deno.land/x until a new release is created.  Is there a way to use the latest changes rather than cloning this repo locally?

**Comment by eveningkid** [comment]
Hi Frederique,

You are very right about this.
I just released a new version, that should do it!

Have a great day
