### ISSUE TITLE
Dependencies are broken

### ISSUE THREAD

**Issue by ph-teven** [eveningkid/denodb#91]
`deno cache https://deno.land/x/denodb@v1.0.4/mod.ts`

results in

`error: Import 'https://deno.land/x/color/index.ts' failed: 404 Not Found`

```
 deno --version                                     
deno 1.2.2
v8 8.5.216
typescript 3.9.2
```

**Comment by eveningkid** [comment]
Hey Stefan,

Thanks for your question.

Just update to 1.0.5 and you should be fine.

Let me know if that fixes it!

Keep in touch

**Comment by eharit** [comment]
Hi Arnaud,
same issue here, and it appears 1.0.5 is not yet available on deno.land. Is there any other way to install v1.0.5?
Cheers
Pal
```
deno 1.2.3
v8 8.6.334
typescript 3.9.2

**Comment by eveningkid** [comment]
Hi Pal,

You are right. I wasn't aware that I needed to add a github web hook for `deno.land` to now fetch new releases (it was automated before).

I added a new tag that is now available there: https://deno.land/x/denodb@v1.0.6.

Enjoy the week :)

**Comment by eveningkid** [comment]
Hello again,

You might encounter an issue with `dex` dependency using 1.0.6.

For denodb to work with the latest deno version, you will need to upgrade to 1.0.7: https://deno.land/x/denodb@v1.0.7.

**Comment by eharit** [comment]
Hi Arnauld,
thank you, I can confirm it's working with 1.0.7!
Pal
