### ISSUE TITLE
Dependencies are broken 

### ISSUE THREAD

**Issue by gmpravin** [eveningkid/denodb#92]
Hey Stefan,

Thanks for your question.

Just update to 1.0.5 and you should be fine.

Let me know if that fixes it!

Keep in touch

_Originally posted by @eveningkid in https://github.com/eveningkid/denodb/issues/91#issuecomment-670973363_

------------------------------------------------------------------
Deno version : 1.2.3

Im updated to 1.0.5 But Still getting error 
error: Import 'https://deno.land/x/color/index.ts' failed: 404 Not Found
Imported from "https://deno.land/x/denodb@v1.0.4/deps.ts:1"

**Comment by eveningkid** [comment]
Hey,

If you're having the same issue that on the other issue, there is no point for duplicates.

Also, you say you updated to 1.0.5 but the right message you're copying here mentions 1.0.4.

**Comment by gmpravin** [comment]
@eveningkid Im updated to 1.0.5, Unexpectly copying massage from another terminal

**Comment by eveningkid** [comment]
I will close this for now as we're moving onto #91 then.

Have a great day :)
