### ISSUE TITLE
Update SQLite dependency 

### ISSUE THREAD

**Issue by dyedgreen** [eveningkid/denodb#95]
There have been some substantial improvements and fixes in the SQLite library, that would be good to see in denodb as well. 

The only change that might need some non-trivial work is that large integers are no returned as `BigInt`, if they overflow JS numbers.

(For reference check https://github.com/dyedgreen/deno-sqlite/releases)

**Comment by eveningkid** [comment]
Hi Tilman,

Wow, August. It's been awhile!

Just upgraded to the latest version.
I was not too sure how to deal with big int. If you know how, let me know.

Your library is only in use in [that file](https://github.com/eveningkid/denodb/blob/master/lib/connectors/sqlite3-connector.ts), which is quite short actually.

If you have any recommendations/suggestions, I'd gladly take them.

Keep in touch

**Comment by dyedgreen** [comment]
Awesome! I’ll let you know if there are any updates again (seeing your commit, I can probably PR them next time 😉).

Regarding the big int: typically, they should just work (if they come from IDs in large tables, the user would just carry them as a value, and as long as they don’t try to do any arithmetic on them everything is fine; if they do want to do arithmetic, it might throw errors, but that’s easily fixed and better than silently overflowing something).
